### ISSUE TITLE
Madanalysis5 stopped working suddenly

### ISSUE THREAD

**Issue by deep20222** [MadAnalysis/madanalysis5#104]
### System Settings

OS : Linux, 

### Describe the bug

I am using madanalysis inside Madgraph. After generating particular process, I am only using madanalysis switch inside madgraph, but the compilation is not happening. After the launch Madanalysis_parton.dat file is generated, but no pdf with different plot is generated. Previously, it is working nicely. Suddenly it has stopped working. I am using Madgraph_aMC_v2_9_6.

### To Reproduce

I am using in Madanalysis in normal mode inside Madgraph. Compilation of Madanalysis is not happening

**Comment by BFuks** [comment]
Hi. 

We will need more information about what you do exactly, as well as all compilation logs. From your explanations, it is impossible for us to reproduce the problem. Please be as specific as possible.

Regards,

Benjamin

**Comment by deep20222** [comment]
Dear Colleague,

Sorry for the inconvenience. Let me attach a screenshot and
madanalysis_parton.dat file if that helps. There is no compilation log file
generated, because the error is happening before compilation with LHE file
as input. I tried to run Madanalysis as a standalone program, but I am
facing some compilation errors in building libraries with multiple cores.
The associated log files  are attached.

Thank you,
With regards,
Deep Ghosh
