### ISSUE TITLE
What is the label for FATJET in Madanalysis5

### ISSUE THREAD

**Issue by umar0341** [MadAnalysis/madanalysis5#118]
### Question

What is the label for FATJET in Madanalysis5

**Comment by jackaraz** [comment]
Depends on how you are constructing a fatjet and which third-party code you are using to do so.

**Comment by umar0341** [comment]
Give me a example

**Comment by umar0341** [comment]
I have 12 jets and want to reconstruct higgs masses using Fatjet

**Comment by jackaraz** [comment]
All information you need is provided in the manuals and tutorials.

**Comment by umar0341** [comment]
i haven't found in manual about FATJET can you share manual

**Comment by jackaraz** [comment]
All the references and links to tutorials are provided in the [README.md](https://github.com/MadAnalysis/madanalysis5#credits).
