### ISSUE TITLE
Unable to install fastjet on MA 2.0.4 beta version (macOS)

### ISSUE THREAD

**Issue by samiur06** [MadAnalysis/madanalysis5#119]
### System Settings

Product Name:	macOS
Product Version:	12.4
Build Version:	21F79
Python 3.8.8
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
MA5 release : 2.0.4 [ 2022/07/18 ]

### Describe the bug

I tried to install fastjet through ma5, but there was an error to do it. 

### To Reproduce

After ma5 started, I ran:
`install fastjet` 
Then the error message came.

I did the same with a stable version, _madanalysis5-1.10.4_ , and installed fastjet successfully through it. The problem occurred only with the 2.0.4 beta version. 

### Log files

[compilation.log](https://github.com/MadAnalysis/madanalysis5/files/9246897/compilation.log)

**Comment by jackaraz** [comment]
Hi @samiur06, I tried to replicate your problem in several different MacOS systems, but every time it seems to be installing fastjet without a problem. Note that v1.10.4 and v2.0 are installing different versions of FastJet. What you can try is to install FastJet with v1.10 and link that fastjet to v2.0 and see if it compiles. This can be done by modifying the following lines:

https://github.com/MadAnalysis/madanalysis5/blob/ea1789b0dd862108808bc4ba2fd5ed67c701e965/madanalysis/input/installation_options.dat#L32-L34

Another option is that other programs, such as ROOT, are clashing with FastJet installation. Could you check what other packages ma5 is able to see? The last option would be installing the latest version of FastJet and `fj-contrib` by yourself, but you will need to compile it with the `-std=c++11` flag to be able to use it within ma5 v2.0, which is not default in FastJet installation. 

Please let me know once you have done these checks and provide as much information as possible. You can run ma5 in debug mode via `./bin/ma5 -d` to retrieve more information.

**Comment by samiur06** [comment]
Hi @jackaraz, thanks for your response. It seems that ROOT isn't clashing with FastJet installation. The error remains with and without ROOT. Other packages linked with v2.0 are Python, GNU GCC g++, GNU Make, Zlib, SciPy, PADForSFS, pyhf, Matplotlib, pdflatex, latex. 

I installed FastJet with v1.10 and could link that FastJet to v2.0 with successful compilation, modifying those lines you suggested. FastJet and fj-contrib both are linked as expected. 

About the last option: I installed the latest version of FastJet and fj-contrib and compiled them with the `-std=c++11` flag. I used fastjet-config file with configure command to do so, specifying the flag.  However, later we can only write the bin path of FastJet on `madanalysis5-2.0.4_beta/madanalysis/input/installation_options.dat`, but not for fj-contrib. Therefore, the latter is not linked to ma5 in this step, and the compilation was incomplete.

**Comment by jackaraz** [comment]
Hi @samiur06, thanks for the details. Unfortunately, since I could not reproduce your issue, I can not help more. But during our tests, we found other bugs that might be related to your issue. Please stay tuned for future releases.

> However, later we can only write the bin path of FastJet on madanalysis5-2.0.4_beta/madanalysis/input/installation_options.dat, but not for fj-contrib. Therefore, the latter is not linked to ma5 in this step, and the compilation was incomplete.

Thanks! I'll make sure to add a way to link external `fj-contrib` in the future release!

**Comment by samiur06** [comment]
This problem has been solved by using the Rosetta terminal, which has the x86_64 architecture, unlike the native terminal of arm64 architecture. I discuss this solution in [_**this issue**_](https://github.com/MadAnalysis/madanalysis5/issues/126). I can now install fastjet within MA5 from the Rosetta terminal. 

Note that MA5 has to run all its commands from this Rosetta environment (i.e., installing dependencies (e.g., fastjet), normal mode command, modifying and running a job in expert mode, etc.); otherwise, user may encounter a linking issue between the dependencies and the Apple computer.
