### ISSUE TITLE
Selecting events based on appearing intermediate state particles

### ISSUE THREAD

**Issue by stevenjeremies** [MadAnalysis/madanalysis5#121]
### Question

Hello,

I am looking at particle-level events of the 'b l+ vl b~ l- vl~ a' final-state process. Contributing Feynman diagrams
can contain no top quark, one (anti)top or a top-antitop-pair. I would like to select only the events containing
a top-antitop-pair. How can I do this selection? I only found selections based on observable values but not on 
the presence of certain particles in the intermediate state. Thanks in advance!

**Comment by stevenjeremies** [comment]
Hello,
I looked through all the possible sources of information and now I know that in order to set cuts on the multiplicity of a given particle I have to set cuts on the observable $N$. However, I was not able to find out how to specify which kind of particle I would like to set a cut on and all of my guesses did not work. For now the syntax of my selection looks like this:

ma5> select N > 1 [interstate]

Can you please tell me how to specify this N to the top quark? Thanks in advance!

**Comment by jackaraz** [comment]
Have you tried `N(t)>1`?

**Comment by stevenjeremies** [comment]
How did I not get this idea.... sry for bothering you with this.
