### ISSUE TITLE
"impossible to execute Matplotlib" when trying to plot log scale lepton invariant mass histogram 

### ISSUE THREAD

**Issue by abhinaya-sinha** [MadAnalysis/madanalysis5#129]
### System Settings

OS: Ubuntu 22.04 LTS
Python version: Python 3.10.4
gcc version: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
MA5 version: 1.9.60

### Describe the bug

Hi, when I try to plot a histogram with logY scaling, I get a matplotlib error, specifically that some 'nonposy' argument was called in the set_ylabel() call.
I'm not sure what the nonposy argument is supposed to be. This problem doesn't occur if I plot without changing the axis scaling.

### To Reproduce

`import pythia8 hepmc file`
`plot M(l+ l-) [ logY ]`
`submit`

### Log files

madanalysis error: `MA5-ERROR: impossible to execute MatPlotLib. For more details, see the log file:`

matplotlib log file:
` BEGIN-STAMP`
`- Producing histo selection_0...`
`- Producing histo selection_1...`
`Traceback (most recent call last):`
`  File ".../madanalysis5/ANALYSIS_0/Output/Histos/MadAnalysis5job_1/all.py", line 10, in <module>`
`    selection_1.selection_1()`
`  File ".../madanalysis5/ANALYSIS_0/Output/Histos/MadAnalysis5job_1/selection_1.py", line 53, in selection_1`
`    plt.gca().set_yscale("log",nonposy="clip")`
`  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 4108, in set_yscale`
`    ax.yaxis._set_scale(value, **kwargs)`
`  File "/usr/lib/python3/dist-packages/matplotlib/axis.py", line 761, in _set_scale`
`    self._scale = mscale.scale_factory(value, self, **kwargs)`
`  File "/usr/lib/python3/dist-packages/matplotlib/scale.py", line 597, in scale_factory`
`    return scale_cls(axis, **kwargs)`
`TypeError: LogScale.__init__() got an unexpected keyword argument 'nonposy' `

**Comment by BFuks** [comment]
Hi,

This has been fixed in MA5 v1.10. The problem was due in changes in Matplotlib. Please update your version of MA5, and things should get back to normal.

Cheers,

Benjamin

**Comment by abhinaya-sinha** [comment]
Thank you!
