### ISSUE TITLE
Please test pyhf v0.7.0 release candidates

### ISSUE THREAD

**Issue by matthewfeickert** [MadAnalysis/madanalysis5#130]
Hi. :wave: As you're a user of `pyhf`

https://github.com/MadAnalysis/madanalysis5/blob/ec5d8b158e33b4178fe04441487ca3265b76d432/requirements.txt#L4

please test the [`pyhf` `v0.7.0` release candidates](https://github.com/scikit-hep/pyhf/releases/tag/v0.7.0rc4) to see if you will be affected by any of the API changes.

```
python -m pip install --upgrade --pre pyhf
```

If you haven't yet, please also consider joining the [pyhf-announcements mailing list](https://groups.google.com/group/pyhf-announcements/subscribe).

This Issue is meant to be helpful to avoid unexpected breaks of your code, but if you find this intrusive or annoying please let us know and we won't bother you again.

**Comment by matthewfeickert** [comment]
Closing as [`pyhf` `v0.7.0`](https://github.com/scikit-hep/pyhf/releases/tag/v0.7.0) is now released. Please consider upgrading to `v0.7.0`!

```
python -m pip install --upgrade pyhf
```

**Comment by jackaraz** [comment]
Thanks, Matthew; the new version of `pyhf` has been tested, and works like a charm will update our requirements accordingly!
