### ISSUE TITLE
How can i plot jets invariant mass to reconstruct W boson mass using Normal Mode MA5. How can apply Cut to get invariant mass peak at W boson mass. I'm using model 2HDM and my process is mu+ mu- > H+H-, where H+ > tb, t > W+ b, W+ > j j

### ISSUE THREAD

**Issue by umar0341** [MadAnalysis/madanalysis5#131]
### Question

How can I plot jet invariant mass to reconstruct W boson mass using Normal Mode MA5? How can apply Cut to get an invariant mass peak at W boson mass? I'm using model 2HDM and my process is mu+ mu- > H+H-, where H+ > tb, t > W+ b, W+ > j j. Kindly send me set of required commands.

**Comment by BFuks** [comment]
Hello,

The best is definitely to read the manual, or at least the documenttiaon shipped with the program.

Regards,

Benjamin

**Comment by umar0341** [comment]
share link

**Comment by BFuks** [comment]
Hi,

Wow, what a rude answer! Maybe investigating how to say "hi"/"hello", "thanks" and signing a message would be a good way to start. Using the internet should help you well here.

Regards,

Benjamin
