### ISSUE TITLE
Error while generating Madanalysis5 output file

### ISSUE THREAD

**Issue by umar0341** [MadAnalysis/madanalysis5#132]
### Question

    * Finalizing all components ...
    * Total number of processed events: 100000.
+----------------------------------------------------------------------------------------------------------------------+
|                              LogReport-Warning                                                                       |
+----------------------------------------------------------------------------------------------------------------------+
| Message                                       NIterations @ File                                              Line   |
|----------------------------------------------------------------------------------------------------------------------|
| PDG ID not found [30443]                      701           DataFormat/PdgTable.cpp                           81     |
| PDG ID not found [9000221]                    411           DataFormat/PdgTable.cpp                           81     |
| PDG ID not found [-14122]                     234           DataFormat/PdgTable.cpp                           81     |
| PDG ID not found [14122]                      218           DataFormat/PdgTable.cpp                           81     |
| PDG ID not found [-4124]                      187           DataFormat/PdgTable.cpp                           81     |
| PDG ID not found [4124]                       159           DataFormat/PdgTable.cpp                           81     |
| PDG ID not found [10331]                      3             DataFormat/PdgTable.cpp                           81     |
| xmin cannot be less than or equal to zero. S  2             /home/au/analysis/mg5v2.7.3/ma5v1.9.60/tools/Sam  80     |
| PDG ID not found [-103122]                    1             DataFormat/PdgTable.cpp                           81     |
| PDG ID not found [-203122]                    1             DataFormat/PdgTable.cpp                           81     |
+----------------------------------------------------------------------------------------------------------------------+
    * Goodbye.
MA5:     *******************************************************
MA5:    Checking SampleAnalyzer output...
MA5:    Extracting data from the output files...
MA5-WARNING: Extra line is found: 1.954166e+00   0.000000e+00
MA5-WARNING: Extra line is found: 1.813032e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.062731e+00   0.000000e+00
MA5-WARNING: Extra line is found: 1.954166e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.247291e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.279861e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.236435e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.247291e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.486134e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.659838e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.670694e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.572986e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.475278e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.703264e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.985532e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.126666e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.061527e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.430648e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.180949e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.104953e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.593495e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.506643e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.419791e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.528356e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.984328e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.408935e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.310023e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.147175e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.223171e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.147175e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.570578e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.559722e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.538009e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.277453e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.308819e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.928842e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.733425e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.232824e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.330532e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.874560e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.026550e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.113402e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.601944e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.732222e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.916782e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.025347e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.525948e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.721365e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.808217e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.786504e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.623657e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.220763e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.676735e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.242476e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.448749e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.807013e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.459606e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.361897e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.644166e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.405323e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.611597e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.351041e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.199050e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.101342e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.416180e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.329328e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.177337e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.546458e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.481319e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.427036e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.470462e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.123055e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.612800e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.949351e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.243680e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.580231e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.612800e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.721365e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.580231e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.972268e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.699652e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.451157e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.733425e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.972268e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.223171e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.223171e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.364305e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.418587e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.331736e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.854051e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.016898e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.071180e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.702060e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.235231e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.985532e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.779259e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.594699e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.540416e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.833541e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.667437e+01   0.000000e+00
MA5-WARNING: Extra line is found: 1.813032e+00   0.000000e+00
MA5-WARNING: Extra line is found: 1.769606e+00   0.000000e+00
MA5-WARNING: Extra line is found: 1.986736e+00   0.000000e+00
MA5-WARNING: Extra line is found: 1.823889e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.084444e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.203866e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.051875e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.269004e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.518703e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.507847e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.540416e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.551273e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.290717e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.562129e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.800972e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.083240e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.942106e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.300370e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.800972e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.887824e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.539213e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.332939e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.419791e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.419791e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.875763e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.419791e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.396875e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.984328e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.973472e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.092893e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.418587e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.353449e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.451157e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.125463e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.004837e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.841990e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.809421e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.265393e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.069976e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.961412e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.178541e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.232824e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.525948e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.460810e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.732222e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.112198e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.515092e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.732222e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.569374e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.786504e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.721365e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.220763e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.513888e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.188194e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.199050e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.861296e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.416180e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.633309e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.676735e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.524745e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.883009e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.329328e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.340185e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.351041e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.394467e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.644166e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.264189e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.872152e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.655022e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.513888e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.557314e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.361897e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.916782e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.264189e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.623657e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.699652e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.525948e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.938495e+00   0.000000e+00
MA5-WARNING: Extra line is found: 6.101342e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.319675e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.829930e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.744282e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.113402e+00   0.000000e+00
MA5-WARNING: Extra line is found: 5.069976e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.603148e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.614004e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.505439e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.852847e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.570578e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.016898e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.234027e+00   0.000000e+00
MA5-WARNING: Extra line is found: 4.353449e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.919189e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.528356e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.072384e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.191805e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.887824e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.866111e+00   0.000000e+00
MA5-WARNING: Extra line is found: 2.996389e+00   0.000000e+00
MA5-WARNING: Extra line is found: 3.187463e+01   0.000000e+00
MA5:    Preparing data for the reports ...
MA5:    Generating all plots ...
Traceback (most recent call last):
  File "./bin/ma5", line 77, in <module>
    madanalysis.core.launcher.LaunchMA5(version, date, ma5dir)
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/core/launcher.py", line 430, in LaunchMA5
    repeat = MainSession(mode,arglist,ma5dir,version,date)
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/core/launcher.py", line 334, in MainSession
    interpreter.cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/interpreter/interpreter.py", line 296, in do_submit
    self.cmd_submit.do(self.split_arg(line),self.history)
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/interpreter/cmd_submit.py", line 64, in do
    return self.do_submit(args,history)
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/interpreter/cmd_submit.py", line 217, in do_submit
    self.CreateReports(args,history,layout)
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/interpreter/cmd_submit.py", line 273, in CreateReports
    if not layout.DoPlots(histopath,modes,output_paths):
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/layout/layout.py", line 177, in DoPlots
    self.plotflow.DrawAll(histo_path,modes,output_paths,ListPlots)
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/layout/plotflow.py", line 170, in DrawAll
    self.DrawROOT(histos,scales,self.main.selection[iabshisto],\
  File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/layout/plotflow.py", line 294, in DrawROOT
    ntot+= histos[ind].summary.array[bin-1]*scales[ind]
IndexError: list index out of range

**Comment by BFuks** [comment]
Hi,

Without more information (and a more polite way to communicate), I am afraid we won't be able to help you.

Regards,

Benjamin

**Comment by BFuks** [comment]
This is a duplicated issue (see #133).
