### ISSUE TITLE
MA5-ERROR: impossible to execute the HEPTopTagger installation command

### ISSUE THREAD

**Issue by samiur06** [MadAnalysis/madanalysis5#137]
### System Settings

Ubuntu 20.04 
Python 3.8.10
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
MA5: MA5 release : 2.0.4 [ 2022/07/18 ]

### Describe the bug

I installed MA5 v2.0 and installed Zlib and fastjet in it. When I tried to install HEPTopTagger, the following message shows up:

```
MA5:    **********************************************************
MA5:                     Installing HEPTopTagger                 
MA5:    **********************************************************
MA5:    Detecting a previous installation ...
MA5:    => not found. OK
MA5:    Creating a devoted folder ...
MA5:    Creating a temporary folder ...
MA5:    Downloading the package ...
MA5-ERROR: impossible to execute the commands: curl -s https://api.github.com/repos/MadAnalysis/HEPTopTagger/releases/latest
MA5:    Installation NOT complete.
MA5:    Elapsed time = 0.00 second
MA5:    => Status: [FAILURE]
MA5:    **********************************************************

```

I installed HEPTopTagger before in other computers without any issue. Can you check if there is an issue with the link `https://api.github.com/repos/MadAnalysis/HEPTopTagger/releases/latest` ?

### To Reproduce

I wrote: `install HEPTopTagger` in ma5 terminal.

**Comment by jackaraz** [comment]
Hi @samiur06, could you try typing `curl -s https://api.github.com/repos/MadAnalysis/HEPTopTagger/releases/latest` in the terminal and tell us what you get? If you can not run this command, it is likely that you are missing modules in your bash, so I suggest updating it. You can check the version of `curl` via the `curl --version` command.

**Comment by samiur06** [comment]
You were right, I updated bash module and installed HEPTopTagger. Thank you for the quick response!
