### ISSUE TITLE
USER DIDN'T WROTE A PROPER TITLE

### ISSUE THREAD

**Issue by umar0341** [MadAnalysis/madanalysis5#138]
**Hi dear Author, I'm working on Madanalysis5 using HEPMC.events files (for the heavy higgs pair production in 2HDM using muon anti muon annihilation) that are generated using Madgraph. But MadAnalysis5 stop producing png and all output files and near to completion madanalysis5 terminated with following massage. Kindly resolve issue
This Massage appears at the end of Madanalysis5**

* Finalizing all components ...
* Total number of processed events: 100000.
+----------------------------------------------------------------------------------------------------------------------+
| LogReport-Warning |
+----------------------------------------------------------------------------------------------------------------------+

MA5-WARNING: Extra line is found: 2.866111e+00 0.000000e+00
MA5-WARNING: Extra line is found: 2.996389e+00 0.000000e+00
MA5-WARNING: Extra line is found: 3.187463e+01 0.000000e+00

File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/layout/plotflow.py", line 170, in DrawAll
self.DrawROOT(histos,scales,self.main.selection[iabshisto],
File "/home/au/analysis/mg5v2.7.3/ma5v1.9.60/madanalysis/layout/plotflow.py", line 294, in DrawROOT
ntot+= histos[ind].summary.array[bin-1]*scales[ind]
IndexError: list index out of range

**After this Madanalysis5 teminated**

**Comment by jackaraz** [comment]
Hi @umar0341, we are not on your computer if you don't tell us which version of the tools you are using we can't help you. If you want help you need to provide all the information to run the program. This means python version, madanalysis version, root, delphes everything you are using. You have been asking the same question over and over with the same attitude, we do not have time to decipher your questions...
