### ISSUE TITLE
Error in installation on cluster

### ISSUE THREAD

**Issue by juhidutta** [MadAnalysis/madanalysis5#143]
### Question

Dear Experts, 

I am facing the following error while installing MadAnalysis (the latest version from github):
 
g++ Root/Test.o  -L/raid05/users/jdutta/madanalysis5-main/tools/SampleAnalyzer/Lib -L/raid05/users/jdutta/madanalysis5-main/tools/SampleAnalyzer/ExternalSymLink/Lib -lroot_for_ma5 -L/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.06-9e6ed/x86_64-centos7-gcc8-opt/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -pthread -lm -ldl -rdynamic -lEG -lcommons_for_ma5 -L/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.06-9e6ed/x86_64-centos7-gcc8-opt/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -pthread -lm -ldl -rdynamic -lEG -o ../Bin/TestRoot
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.06-9e6ed/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_terminate()'
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.06-9e6ed/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.06-9e6ed/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_initialize()'
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.06-9e6ed/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const'
collect2: error: ld returned 1 exit status
make: *** [link] Error 1

My system settings are as follows:

Operating System: centOS
Python version: Python 3.7.6
gcc version: 8.3.0
MadAnalysis 5 version:  MA5: MA5 release : 1.10.4 [ 2022/07/18 ]
Delphes-Delphes-3.5.0

Could you please kindly let me know how may I resolve this issue? 

Looking forward to your help and advice,

With best regards,
Juhi

**Comment by jackaraz** [comment]
Hi Juhi, this looks like a root issue where it looks like your machine is missing some requirements to compile root. If you absolutely need root (note that you can use MadAnalysis without it), I suggest checking ROOT's home page and making sure that you fulfil all their requirements.

**Comment by juhidutta** [comment]
Hi Jack,

Thank you for the prompt response. Could you please let me know what would
the command be for installation without root? It seems to auto detect the
Root 6 implementation.

Best regards,
Juhi

**Comment by jackaraz** [comment]
Hi Juhi, you can turn off ROOT or set any specific ROOT that you like to use from here:

https://github.com/MadAnalysis/madanalysis5/blob/ec5d8b158e33b4178fe04441487ca3265b76d432/madanalysis/input/installation_options.dat#L10-L12

**Comment by juhidutta** [comment]
Hi Jack,

Thank you, this solves my problem.

Best regards,
Juhi
