### ISSUE TITLE
Issue with scipy and matplotlib 

### ISSUE THREAD

**Issue by meshoaib** [MadAnalysis/madanalysis5#147]
### Question

Dear experts, 
I have working MA5 with the following details, 

**MA 5 Version:**
MA5 release : 1.8.58

**Python versions:**
Python 2.7.18
Python 3.8.10

**gcc/c++ version**
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

Third party software's that is Delphes (did manually, automatically did not worked), fastjet, phyf are also installed and give "OK" In general, in my system "scipy" and matplotlib are installed and working properly. 

I also tried "python3 -m pip install -r requirements.txt" with result "Requirement already satisfied"

![Screenshot from 2022-11-06 14-17-38](https://user-images.githubusercontent.com/6188567/200163031-2d0be000-b693-47d3-9db3-a334e9aa8cb6.png)

When in MA5, i tried to install PAD, it says scipy is not install ... so i am wondering how to fix it

**Comment by jackaraz** [comment]
Hi @meshoaib, Ma5 v1.8 is extremely old. Could you please try v1.10 and let us know if it still has problems? Thanks

**Comment by meshoaib** [comment]
Thanks for reply. 

I tried both versions  v1.9.60 and v1.10

1) v1.9.60 says python "six" module is not found but its installed with version 1.14.0

2) v1.10 says ...

./bin/ma5 
Python release 2.7.18 (default, Jul  1 2022, 12:27:04) [GCC 9.4.0] is detected.
MadAnalysis 5 works only with Python version 3.6 or more recent version. Please upgrade your Python installation.

But in system both Python 2.7.18 and Python 3.8.10 are working ... both are latest updated version

**Comment by meshoaib** [comment]
> Ma5 v1.8

according to my experience Ma5 v1.8  is most stable version than v1.9 and v1.10 ... that's why i adopted v1.8

**Comment by meshoaib** [comment]
> Hi @meshoaib, Ma5 v1.8 is extremely old. Could you please try v1.10 and let us know if it still has problems? Thanks

Thanks it worked with command: python3 ./bin/ma5 

Other question is: when someone need "Delphes-MA5tune" and "PADForMA5tune" to be in "OK" state?

**Comment by jackaraz** [comment]
Hi @meshoaib, if you let us know when you observe an instability, it will help everyone. 

* `Ma5Tune` is designed for 7-8 TeV analyses.
* MadAnalysis can not detect all the python versions available on your machine; it can only detect the default one set in your bash profile and uses that. This is, by default, python version 2 in most of the OSs; if you dont change it. `six` is to adapt python 2 compatible environments for python 3, so you need to install it before using MadAnalysis 5 since we are deprecating the usage of python 2.

**Comment by meshoaib** [comment]
> Hi @meshoaib, if you let us know when you observe an instability, it will help everyone.
> 
> * `Ma5Tune` is designed for 7-8 TeV analyses.
> * MadAnalysis can not detect all the python versions available on your machine; it can only detect the default one set in your bash profile and uses that. This is, by default, python version 2 in most of the OSs; if you dont change it. `six` is to adapt python 2 compatible environments for python 3, so you need to install it before using MadAnalysis 5 since we are deprecating the usage of python 2.

Is there any complete tutorial and analysis that can be followed for practice means to see complete results at first level before jumping to new problem ...
2nd--- if i do an analysis endogenously using MA5, is that publishable?

**Comment by jackaraz** [comment]
Hi @meshoaib, [PAD](http://madanalysis.irmp.ucl.ac.be/wiki/PublicAnalysisDatabase) is full of analyses designed to recast given experimental analyses and validated according to them. Public codes are using either Delphes or [SFS (arXiv:2006.09387 [hep-ph])](https://arxiv.org/abs/2006.09387) for detector simulation, and all available codes can be downloaded via the `install PAD` command. Once they are downloaded, codes can be found under the `tools/PADForSFS` or `tools/PAD` folders. Also, as written in the [README](https://github.com/MadAnalysis/madanalysis5#readme) file, tutorials can be found [here](https://madanalysis.irmp.ucl.ac.be/wiki/tutorials). Additionally, the [user manual and other publications based on MadAnalysis 5](https://github.com/MadAnalysis/madanalysis5#credits) are good sources.

> if i do an analysis endogenously using MA5, is that publishable?

Of course, the normal mode is constantly validated and monitored against any possible bugs, and the expert mode mostly depends on your coding skills, so assuming that you have implemented and validated your analysis, the result should be correct. Also, given that there are more than 900 peer-reviewed publications that are using MadAnalysis 5 should be an indication. As always, please let us know if you see any possible issues with the software.
