### ISSUE TITLE
Issue: Using loaded dataset to set cuts without reload them

### ISSUE THREAD

**Issue by Mustafa-Ashry** [MadAnalysis/madanalysis5#148]
### Question

Hello,

In Madgraph, we can generate a small dataset with some customized settings, then we can used the 'multirun' command to generate many datasets successively. I wonder if I can reuse the same one-time loaded dataset(s) to insert some cuts without the need to reload it again, as sometimes one works on a large dataset which takes long time to load in Madanalysis.

Thanks and Regards

Mustafa

**Comment by jackaraz** [comment]
Hi @Mustafa-Ashry, as far as I understand, you want to analyse multiple dataset files within the same analysis under same tag, correct? You can add as many files as you want with as many tags as you like in Ma5. For instance;
```
import first_smp.hepmc.gz as my_sample
import second_smp.hepmc.gz as my_sample
import third_smp.hepmc.gz as my_sample
```
This will create a tag named `my_sample` and collect all these files under this sample name. You can also do the following
```
import /PATH/TO/MY/SAMPLES/* as my_sample
```
which will do the same thing as before. You can add different tags as well if you want to compare two (or more) types of input.

hope it helps
cheers

**Comment by jackaraz** [comment]
Hi @Mustafa-Ashry, you can use the `resubmit` command after adding extra cuts or plotting commands, but this will rerun all the samples from scratch. We don't have a way to top-up the existing histograms or cutflows; the analysis has to run through the entire sample every time you want to add/subtract something.

**Comment by Mustafa-Ashry** [comment]
Thank you @jackaraz , this was my question. Is there any plan working on this in the future?
Regards
Mustafa

**Comment by jackaraz** [comment]
Hi @Mustafa-Ashry, not at the moment, but feel free to [contribute](https://github.com/MadAnalysis/madanalysis5/blob/main/doc/CONTRIBUTING.md). We are always open to new ideas and hands that are willing to improve Ma5.

**Comment by Mustafa-Ashry** [comment]
@jackaraz But I noticed that you imported definitely the hepmc files in your examples above, did you mean they are the default or the best choice to work with?
Mustafa

**Comment by jackaraz** [comment]
my pleasure

**Comment by jackaraz** [comment]
You can work with any type of file in MadAnalysis; it was just the first type that came to my mind.

**Comment by Mustafa-Ashry** [comment]
@jackaraz Ummm, some colleague told me that working with the lhco files usually takes much shorter times than the root files and I though that working with the hepmc is even much more efficient, any comments about this?
Thanks

**Comment by jackaraz** [comment]
This highly depends on the analysis that you are trying to do. HEPMC file includes a huge amount of information. Delphes applies detector simulation to convert that into a ROOT file, which can be large as well. If you don't need to use jet constituent information, I would suggest using [SFS (arXiv: 2006.09387 [hep-ph])](https://arxiv.org/abs/2006.09387) to convert your HEPMC file into an LHE file and do your analysis on that. This will be the fastest option.

**Comment by Mustafa-Ashry** [comment]
Great! Thank you for your your information.
Best regards
Mustafa
