### ISSUE TITLE
Install zlib FAILURE

### ISSUE THREAD

**Issue by ArturU043** [MadAnalysis/madanalysis5#150]
### System Settings

macOS 12.0.1
Python 3.9 and Apple clang version 13.1.6 (clang-1316.0.21.2.5)
ma5 verison 1.10.4

### Describe the bug

Trying to install zlib : 

MA5:    **********************************************************
MA5:                         Installing zlib                     
MA5:    **********************************************************
MA5:    Detecting a previous installation ...
MA5:    => not found. OK
MA5:    How many cores would you like to use for the compilation ? default = max = 4
   => Answer: 4
MA5:    => Number of cores used for the compilation = 4
MA5:    **********************************************************
MA5:    Creating a devoted folder ...
MA5:    Creating a temporary folder ...
MA5:    Downloading the package ...
MA5:     - 1/1 http://zlib.net/zlib-1.2.12.tar.gz ...
MA5-WARNING: Impossible to access the url: http://zlib.net/zlib-1.2.12.tar.gz
MA5-WARNING: New attempt to access the url: http://zlib.net/zlib-1.2.12.tar.gz
MA5-WARNING: Impossible to access the url: http://zlib.net/zlib-1.2.12.tar.gz
MA5-WARNING: New attempt to access the url: http://zlib.net/zlib-1.2.12.tar.gz
MA5-WARNING: Impossible to access the url: http://zlib.net/zlib-1.2.12.tar.gz
MA5-WARNING: Impossible to download the package from http://zlib.net/zlib-1.2.12.tar.gz to /var/folders/rl/c_v3j6t97j51xfs8rjlh0sfx2djbcf/T/MA5_downloads/zlib.tar.gz
MA5-WARNING: Error(s) occured during the installation.
MA5:    Installation NOT complete.
MA5:    Elapsed time = 12.32 seconds
MA5:    => Status: [FAILURE]
MA5:    **********************************************************
MA5: 
ma5>version
MA5-WARNING: Command "version" not implemented, please try again.

### To Reproduce

try : install zlib (on version 1.10.4)

Url does not exist (error 404) 
http://zlib.net/zlib-1.2.12.tar.gz

**Comment by jackaraz** [comment]
Hi @ArturU043, thanks for letting us know; it seems like they updated `zlib` last month so that the new address will be [zlib.net/zlib-1.2.13.tar.gz](https://zlib.net/zlib-1.2.13.tar.gz). Will update ma5 accordingly. 

For the users who are facing the same issue please replace the following 
https://github.com/MadAnalysis/madanalysis5/blob/ec5d8b158e33b4178fe04441487ca3265b76d432/madanalysis/install/install_zlib.py#L34-L43
`zlib-1.2.12` to `zlib-1.2.13` until we release a new update.
