### ISSUE TITLE
Error during PAD installation

### ISSUE THREAD

**Issue by luigidr0** [MadAnalysis/madanalysis5#155]
### System Settings

macOS v10.13.6

Python 2.7.13 :: Anaconda 4.4.0 (x86_64)

gcc/c++ version:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

MA5: MA5 release : 1.9.60 [ 2021/12/13 ]

### Describe the bug

I am trying to install PAD on my mac laptop. The installation stops with an error:

MA5:    Unpacking the package ...
MA5:    Configuring the package ...
MA5:    Building the package ...
MA5-ERROR: impossible to build the project. For more details, see the log file:
MA5-ERROR: /Users/luigi/madanalysis5/tools/PAD/Build/compilation.log
MA5:    Installation NOT complete.
MA5:    Elapsed time = 2 minutes 12 seconds
MA5:    => Status: [FAILURE]

### To Reproduce

install PAD

### Log files

content of compilation.log:

-e [1;33m--------------------------------------------------------
-e [1;33m--------------------------------------------------------
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o Main/main.o -c Main/main.cpp
-e                       Compilation                       
-e                 Building MadAnalysis Job                
-e --------------------------------------------------------[0;39m
-e --------------------------------------------------------[0;39m
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_conf_2016_086.o -c SampleAnalyzer/User/Analyzer/atlas_conf_2016_086.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_conf_2019_040.o -c SampleAnalyzer/User/Analyzer/atlas_conf_2019_040.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_conf_2020_002.o -c SampleAnalyzer/User/Analyzer/atlas_conf_2020_002.cpp
In file included from Main/main.cpp:12:
In file included from ./SampleAnalyzer/User/Analyzer/analysisList.h:30:
./SampleAnalyzer/User/Analyzer/atlas_susy_2018_04.h:19:21: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
 MAint32 event_num = 0;
                   ^
1 warning generated.
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_exot_2014_06.o -c SampleAnalyzer/User/Analyzer/atlas_exot_2014_06.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_exot_2015_03.o -c SampleAnalyzer/User/Analyzer/atlas_exot_2015_03.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_exot_2016_25.o -c SampleAnalyzer/User/Analyzer/atlas_exot_2016_25.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_exot_2016_27.o -c SampleAnalyzer/User/Analyzer/atlas_exot_2016_27.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_exot_2016_32.o -c SampleAnalyzer/User/Analyzer/atlas_exot_2016_32.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_exot_2018_30.o -c SampleAnalyzer/User/Analyzer/atlas_exot_2018_30.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_susy_2015_06.o -c SampleAnalyzer/User/Analyzer/atlas_susy_2015_06.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_susy_2016_07.o -c SampleAnalyzer/User/Analyzer/atlas_susy_2016_07.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_susy_2018_04.o -c SampleAnalyzer/User/Analyzer/atlas_susy_2018_04.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_susy_2018_06.o -c SampleAnalyzer/User/Analyzer/atlas_susy_2018_06.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_susy_2018_17.o -c SampleAnalyzer/User/Analyzer/atlas_susy_2018_17.cpp
In file included from SampleAnalyzer/User/Analyzer/atlas_susy_2018_04.cpp:1:
./SampleAnalyzer/User/Analyzer/atlas_susy_2018_04.h:19:21: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
 MAint32 event_num = 0;
                   ^
SampleAnalyzer/User/Analyzer/atlas_susy_2018_17.cpp:258:16: warning: unused variable 'npre50j' [-Wunused-variable]
 unsigned int npre50j = sep_jets.size();
              ^
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_susy_2018_32.o -c SampleAnalyzer/User/Analyzer/atlas_susy_2018_32.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.o -c SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp
1 warning generated.
1 warning generated.
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_b2g_12_012.o -c SampleAnalyzer/User/Analyzer/cms_b2g_12_012.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_b2g_12_022.o -c SampleAnalyzer/User/Analyzer/cms_b2g_12_022.cpp
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:335:7: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
 for(auto jet: jets)
     ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:335:15: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
 for(auto jet: jets)
             ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:670:11: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto tJet : SoftJets)
         ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:670:21: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (auto tJet : SoftJets)
                   ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:706:11: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
     for(auto track: tracks)
         ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:706:21: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
     for(auto track: tracks)
                   ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:719:11: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
     for(auto CurrentElectron : InitialElectrons)
         ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:719:32: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
     for(auto CurrentElectron : InitialElectrons)
                              ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:748:11: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
     for(auto CurrentMuon : InitialMuons)
         ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:748:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
     for(auto CurrentMuon : InitialMuons)
                          ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:778:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
   for (auto tElec : BaselineElectrons)
        ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:778:21: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
   for (auto tElec : BaselineElectrons)
                   ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:805:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
   for (auto tMuon : BaselineMuons)
        ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:805:21: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
   for (auto tMuon : BaselineMuons)
                   ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:827:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
   for (auto tJet : SoftJets)
        ^
SampleAnalyzer/User/Analyzer/atlas_susy_2019_08.cpp:827:20: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
   for (auto tJet : SoftJets)
                  ^
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_b2g_14_004.o -c SampleAnalyzer/User/Analyzer/cms_b2g_14_004.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_b2g_17_014.o -c SampleAnalyzer/User/Analyzer/cms_b2g_17_014.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_12_047.o -c SampleAnalyzer/User/Analyzer/cms_exo_12_047.cpp
16 warnings generated.
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_12_048.o -c SampleAnalyzer/User/Analyzer/cms_exo_12_048.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_16_010.o -c SampleAnalyzer/User/Analyzer/cms_exo_16_010.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_16_012.o -c SampleAnalyzer/User/Analyzer/cms_exo_16_012.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_16_022.o -c SampleAnalyzer/User/Analyzer/cms_exo_16_022.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_17_009.o -c SampleAnalyzer/User/Analyzer/cms_exo_17_009.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_17_015.o -c SampleAnalyzer/User/Analyzer/cms_exo_17_015.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_17_030.o -c SampleAnalyzer/User/Analyzer/cms_exo_17_030.cpp
clang++ -Wall -O3 -fPIC -I/Users/luigi/madanalysis5/tools/ -I./ -pthread -stdlib=libc++ -m64 -I/Users/luigi/root-5.34.36/include -o SampleAnalyzer/User/Analyzer/cms_exo_19_002.o -c SampleAnalyzer/User/Analyzer/cms_exo_19_002.cpp
SampleAnalyzer/User/Analyzer/cms_exo_17_030.cpp:547:19: error: expected expression
               trips.push_back({[jetcoll.at](http://jetcoll.at/)(i), [jetcoll.at](http://jetcoll.at/)(j), [jetcoll.at](http://jetcoll.at/)(k)});
                               ^
SampleAnalyzer/User/Analyzer/cms_exo_17_030.cpp:633:57: error: expected expression
       if (matched_jets1.size() == 3) matched_trips.push_back({[matched_jets1.at](http://matched_jets1.at/)(0), [matched_jets1.at](http://matched_jets1.at/)(1), [matched_jets1.at](http://matched_jets1.at/)(2)});
                                                              ^
SampleAnalyzer/User/Analyzer/cms_exo_17_030.cpp:634:57: error: expected expression
       if (matched_jets2.size() == 3) matched_trips.push_back({[matched_jets2.at](http://matched_jets2.at/)(0), [matched_jets2.at](http://matched_jets2.at/)(1), [matched_jets2.at](http://matched_jets2.at/)(2)});
                                                              ^
SampleAnalyzer/User/Analyzer/cms_exo_17_030.cpp:635:57: error: expected expression
       if (matched_jets3.size() == 3) matched_trips.push_back({[matched_jets3.at](http://matched_jets3.at/)(0), [matched_jets3.at](http://matched_jets3.at/)(1), [matched_jets3.at](http://matched_jets3.at/)(2)});
                                                              ^
SampleAnalyzer/User/Analyzer/cms_exo_17_030.cpp:636:57: error: expected expression
       if (matched_jets4.size() == 3) matched_trips.push_back({[matched_jets4.at](http://matched_jets4.at/)(0), [matched_jets4.at](http://matched_jets4.at/)(1), [matched_jets4.at](http://matched_jets4.at/)(2)});
                                                              ^
5 errors generated.
make: *** [SampleAnalyzer/User/Analyzer/cms_exo_17_030.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by jackaraz** [comment]
Hi @luigidr0, I see that you are using an old version of ma5. With the new version, 1.10, we enabled `c++11` features to be used in PAD analyses. All the warnings you see are because the old version of ma5 is not compiled with `c++11`. Your problem should be solved if you update your ma5. Or you can simply remove the problematic analyses if you insist on using the old version.

**Comment by luigidr0** [comment]
Hi @jackaraz, thanks for the suggestion. I have just checked that the newest version does not have this issue. Thanks.
