### ISSUE TITLE
Fastjet interface delphes 

### ISSUE THREAD

**Issue by Es-said** [MadAnalysis/madanalysis5#158]
### Question

Hi MadAnalysis5 team,
Actually, i little bit confused during read MA5 manual, in how to reconstruction jets. all works that i have read,  i found they use after hadronisation and showering, fastjet + delphes to reconstructing jets in same time, my question is that delphes_card take on consederation fastjet(b-tagging-, tau-tagging, mistag_rates ) without need to passe this step "set main.fastsim.package = fastjet" or i have to generate hadron_level events, and i use fastjet following this command "set main.fastsim.package = fastjet" then i store reconstruction jets events following by interfacing this events storing in delphes level via command "set main.fastsim.package = delphes" ?

**Comment by jackaraz** [comment]
Hi @Es-said I dont think I understand what you are trying to do. Delphes has its own fastjet interface and options for clustering is handled through delphes card. Usage of fastjet through madanalysis is completely independent of delphes, you dont need delphes to use fastjet. You can check [this paper](https://arxiv.org/abs/2006.09387) for details on how to use fastjet within madanalysis. Finally in principle you can cluster any kind of event but ME level events are already contain hard events so we dont usually cluster those (it might be useful in case of ISR or FSR i.e. in NLO computation), showered events contain soft objects which are not “safe” to use so you should cluster them to ensure IRC safety.

**Comment by Es-said** [comment]
thank you Jack for your reply, 
Now, i understand, dephes has its own  fastjet interface, which independant to Fastjet. Actually, i have read how to cluster jets using Fastjet also i check algorithm and new command available in
new versions of MadAnalysis 5, but what make me confused is almost of papers when i check them i found that they use clustering at delphes level, Now i want to understood   what is the different between  events clustering after hadron level using Fastjet and  clustring events at delphes level, and what is the adventage of each case?

**Comment by jackaraz** [comment]
Hi @Es-said, delphes is a software that implements detector simulation on your showered events. Other than that it uses fastjet as its normally used. The paper I linked in the last message might clarify this.

**Comment by Es-said** [comment]
okey, when delphes uses fastjets as its normal used is there a away to define b–tagging efficiency and the mistag rates of the charm or light quark jet as a b-jet?

**Comment by jackaraz** [comment]
Hi @Es-said , that is the entire purpose of delphes. But you dont need delphes to do that, as described in arXiv:2006.09387 You can easily do that within madanalysis as well.

**Comment by Es-said** [comment]
Hi Jack,
yes, it's easy to do that with MA5 using FastJet package as described in your work arXiv:2006.09387, but i want do it with delphes card but i don't know is it possible, and if yes i don't know how, i check delphes manual but the way to do that isn't described.

**Comment by jackaraz** [comment]
Hi @Es-said , then I suggest following their tutorials and documentation. I’m sure they provided everything you might need.

**Comment by Es-said** [comment]
Hi Jack,
i have one more question on how choosing Standard model background can mimic our signal, the information that i have is background should have same final state my signal some time i found paper didn't respect that spectially final state contain jets.
i give you an example that i have read, signal final state [bbw-b~b~w+]  they give background  p p  > (h>b b~) Z+jets  that i don't understand. if you can can explain a little bit how we choose background thank you so much.

**Comment by jackaraz** [comment]
Hi @Es-said, for background estimation, I suggest reading experimental papers using similar final state/phase space with you. Note that it does not need to be exactly the same as yours because showering will add a ton of multiplicity to especially your jets in your example, `bbw` means you have either jets + b or lep+nu+b type of background, so you should consider all sources that can bring leptons and/or a large number of jets. `p p > (h>b b~) Z+jets` means Z can go to 2l as well as 2jets for phase spaces with low lepton resolution your signal becomes identical to this background. So as I said, check the experimental analyses and see which backgrounds have a large contribution to this final state in question and then, one by one, generate your background samples (note that generating bkg is not an easy task you need to keep an eye on your DJR distribution which can be generated via ma5).

**Comment by Es-said** [comment]
thank you Jack,
for this background p p > (h>b b~) Z+jets, for "jets" how i can know how many jet should i have generate when i start generating this process by madgraph?

**Comment by jackaraz** [comment]
Hi @Es-said, as a rule of thumb, we generate 0 + 1 + 2 + 3 jet sample and check DJR with that but depending on your problem and the phase space you are looking for, this can be less.

**Comment by Es-said** [comment]
what is DJR distribution (first time i heard about it)  and how i can check it?
I'm sorry about so many questions

**Comment by jackaraz** [comment]
Hi @Es-said, please check ["Chapter 4: Using FastJet"](https://madanalysis.irmp.ucl.ac.be/wiki/tutorials) in our tutorials, which will provide you with a head start.

**Comment by Es-said** [comment]
thank you Jack
