### ISSUE TITLE
Extract observable specific data from event shower.

### ISSUE THREAD

**Issue by pimherbschleb** [MadAnalysis/madanalysis5#159]
I'm sorry if this question could be better asked at madgraph as opposed to madanalysis, but I'm quite new and I don't understand the inner workings of either yet.
I'm trying to shower a particle level event and from that event extract information on the observables e.g. differential cross section at different centre of mass energies or (and I don't understand jets that well yet) transverse momenta of certain jets. Essentially I would like the data out of which the histograms are made in the pdf report at parton or hadron level.
Could you explain how to get this data in a way that a person who is not that familiar with coding could apply.
I have heard of lhe reading software and for the unweighted events I've been able to extract this information, but not on the showered events. Thanks in advance.

best,
pim herbschleb

**Comment by jackaraz** [comment]
Hi @pimherbschleb, all the data is stored in the `Output/SAF/<sample name>` folder. There you can find `Histos.saf` file which contains all the information that is used to generate the histograms in your report. If you like to have a package to parse that file I suggest [`ma5-expert`](https://github.com/MadAnalysis/ma5_expert) plugin.

**Comment by pimherbschleb** [comment]
Hi Jack Y. Araz,

thank you for the response. Could you tell me where I can find this output file? In magraph I can generate an output file with a certain name and in it are events, but not something like Output/SAF. I do have a HEPTools file, but I'm guessing it's not in there. Thanks in advance!

cheers,
pim

________________________________
Van: Jack Y. Araz ***@***.***>
Verzonden: dinsdag 20 december 2022 14:11
Aan: MadAnalysis/madanalysis5 ***@***.***>
CC: pimherbschleb ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MadAnalysis/madanalysis5] Extract observable specific data from event shower. (Issue #159)


Hi @pimherbschleb<https://github.com/pimherbschleb>, all the data is stored in the Output/SAF/<sample name> folder. There you can find Histos.saf file which contains all the information that is used to generate the histograms in your report. If you like to have a package to parse that file I suggest ma5-expert<https://github.com/MadAnalysis/ma5_expert> plugin.

**Comment by jackaraz** [comment]
Hi @pimherbschleb, madgraph might be removing the raw files generated by madanalysis and using only the PDF or HTML file, but I'm sure they are storing it somewhere in your event folder it is unlikely that they delete the madanalysis workspace. Normaly when you run madanalysis standalone you can find all the information about your analysis in the path I wrote above.

**Comment by pimherbschleb** [comment]
Dear Jack,

I do have two files that I think contain the data to make the histograms, they are tag_1_pythia8_BasicReco.lhe.gz and tag_1_pythia8_events.hepmc.gz. Would these be the files that you're referring to? If so, I tried to open/unzip them, but I'm running into some problems. Apparently the lhe.gz file has symbolic links, which I don't know how to deal with and I'm not sure how to extract information from a hepmc file. Would this "expert mode" you're referring to be used for this and is there a good tutorial to learn how to use it? Thanks again for adressing my query.

cheers,
pim
________________________________
Van: Jack Y. Araz ***@***.***>
Verzonden: dinsdag 10 januari 2023 14:43
Aan: MadAnalysis/madanalysis5 ***@***.***>
CC: pimherbschleb ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MadAnalysis/madanalysis5] Extract observable specific data from event shower. (Issue #159)


Hi @pimherbschleb<https://github.com/pimherbschleb>, madgraph might be removing the raw files generated by madanalysis and using only the PDF or HTML file, but I'm sure they are storing it somewhere in your event folder it is unlikely that they delete the madanalysis workspace. Normaly when you run madanalysis standalone you can find all the information about your analysis in the path I wrote above.

**Comment by jackaraz** [comment]
I'm assuming this issue has been resolved, closing the topic. Please don't hesitate to reopen if you need more information on this specific title.
