### ISSUE TITLE
DJR distrubution

### ISSUE THREAD

**Issue by Es-said** [MadAnalysis/madanalysis5#160]
### System Settings

.

### Describe the bug

Hi Jack,
i have generate p p > t t~ + jets, in order to check the smoothness of DJR,  i start by running MA5 ./ma5 -H followed by command 
ma5>set main.merging.check = true
ma5>set main.merging.njets = 3
ma5>import /home/said/Desktop/MG5_aMC_v3_4_1/HEPTools/madanalysis5/madanalysis5/samples/tag_1_pythia8_events.hepmc.gz
ma5>submit djrE
 the plots of DJR are attached here

my problem is how i can know DJR are smooth or not?

### To Reproduce

[main.pdf](https://github.com/MadAnalysis/madanalysis5/files/10278801/main.pdf)

### Log files

[main.pdf](https://github.com/MadAnalysis/madanalysis5/files/10278812/main.pdf)

**Comment by jackaraz** [comment]
Hi @Es-said , first of all this is not a bug. Please use correct channels to report your issue. Secondly we can not help with your research this channel is only for the issues regarding madanalysis software, I suggest reading about differential jet distributions.
