### ISSUE TITLE
Suggestion about the tutorial website

### ISSUE THREAD

**Issue by SiWang4phys** [MadAnalysis/madanalysis5#162]
### Question

Hi,

On the tutorial page, I just want to take a look at the file, but I don’t want to download it.
See page:
https://madanalysis.irmp.ucl.ac.be/wiki/tutorials

It's very annoying every time it downloads the file.
Is there any way to solve it? Just open a new tutorial content not download the tutorial.

Thank you!
Si

**Comment by jackaraz** [comment]
Hi @SiWang4phys, our website is based on `trac`; we do not control such things; they do. But Ma5 is an open source package that is driven by the community contribution, if you like to design a new, less annoying website for the software you are very welcome to do so.
