### ISSUE TITLE
Signal xsection not defined

### ISSUE THREAD

**Issue by ArturU043** [MadAnalysis/madanalysis5#165]
### System Settings

MACOS 12.0.1
python 3.9 
clang-1316.0.21.2.5
MA5: MA5 release : 1.10.4 [ 2022/07/18 ]

### Describe the bug

I loaded a hepmc, defined a xsec 
submited an analysis : atlas_conf-2019_40 (one of the standard ones inside the padsfs fodler) 

But at the end I get : signal x sec not defined 

Terminal : important parts in bold text

**ma5>import /Users/acordeir/Documents/LPNHE/ATLAS/MA5 as DMsignalYY
MA5:    -> Storing the file 'DMtYY.hepmc.gz' in the dataset 'DMsignalYY'.
ma5>set DMsignalYY.xsection = 0.001831**
ma5>set main.recast.add.extrapolated_luminosity = 300 3000
ma5>set main.recast.error_extrapolation = linear 
ma5>submit
MA5:    Creating folder 'ANALYSIS_0'...
MA5: Would you like to edit the recasting Card ? (Y/N)
Answer: Y
MA5:    Getting the list of delphes simulation to be performed...
MA5:    **********************************************************
MA5:                   v1.2+ detector simulations                
MA5:    **********************************************************
MA5:    **********************************************************
MA5:        vSFS running of the PAD on events generated with     
MA5:                 sfs_card_atlas_susy_2016_07.ma5             
MA5:    **********************************************************
...
      <>    Analysis: ATLAS-SUSY-16-07                <>
      <>             arXiv:1712.02332                 <>
      <>             (multijet + MET)                 <>
      <>   Recasters: G. Chalons & H. Reyes-Gonzales  <>
      <>   Contact: fuks@lpthe.jussieu.fr             <>
      <>   Based on MadAnalysis 5 v1.6                <>
      <>   For more information, see                  <>
      <>   http://madanalysis.irmp.ucl.ac.be/wiki/    <>
      <>   /PhysicsAnalysisDatabase                   <>
      <><><><><><><><><><><><><><><><><><><><><><><><><>
END   Initialization
    * Running over files ...
    * 1/1  /Users/acordeir/Documents/LPNHE/ATLAS/MA5/DMtYY.hepmc.gz
    |
| PDG ID not found [-4124]                      3             DataFormat/PdgTable.cpp                           98     |
+----------------------------------------------------------------------------------------------------------------------+
    * Goodbye.
MA5:     *******************************************************
MA5:    * Using Uncertainties and Higher-Luminosity Estimates
MA5:      Please cite arXiv:1910.11418 [hep-ph]
MA5:    Calculation of the exclusion CLs for a lumi of default
**MA5:    Signal xsection not defined. The 95% excluded xsection will be calculated.**
MA5:    Calculation of the exclusion CLs for a lumi of 300.0
MA5:    Signal xsection not defined. The 95% excluded xsection will be calculated.
MA5:    Calculation of the exclusion CLs for a lumi of 3000.0
MA5:    Signal xsection not defined. The 95% excluded xsection will be calculated.

### To Reproduce

I guess do the same as in the teminal.

**Comment by BFuks** [comment]
I have retried with v1.10.7 and I actually cannot reproduce the issue. Jack tried with v1.10.4 and cannot do it either. Can you please type ```display DMsignaYY``` to check that the cross section has been correctly read. If yes, can you redo the full thing in debug mode, and dump the screen output (```./bin/ma5 -Rd```). 

Thanks in advance.

**Comment by jackaraz** [comment]
That's great that it worked out @ArturU043; please let us know if you discover any other issues!
