### ISSUE TITLE
Passing delphes_events.lhco through MA5

### ISSUE THREAD

**Issue by Karabo-Mosala** [MadAnalysis/madanalysis5#166]
### Question

Hi,

When I pass pythia8 output through Delphes, I get error as given in "tag_1_delphes.log"
```
`Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for ExRootAnalysis/ExRootTreeReader.h
   requested to autoload type ExRootTreeReader
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for ExRootAnalysis/ExRootTreeWriter.h
   requested to autoload type ExRootTreeWriter
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for ExRootAnalysis/ExRootTreeBranch.h
   requested to autoload type ExRootTreeBranch
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for ExRootAnalysis/ExRootResult.h
   requested to autoload type ExRootResult
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for ExRootAnalysis/ExRootClassifier.h
   requested to autoload type ExRootClassifier
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for ExRootAnalysis/ExRootFilter.h
   requested to autoload type ExRootFilter
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for ExRootAnalysis/ExRootProgressBar.h
   requested to autoload type ExRootProgressBar`
```
........
.............so on

When I convert delphes output file "delphes_events.root" file into lhco format to pass it through MA5, I get zero cross section.

I have shared above the error part of delphes log file in case if this is the reason. 
May be I am supposed to ask this question at delphes platform but still I am here since MA5 is involved.

Thanks

**Comment by jackaraz** [comment]
Hi @Karabo-Mosala, as far as I know, the root file does not contain cross-section information. Thus you need to set the sample cross-section by hand when you use converted files. You can use the following command
```
import /SAMPLE/PATH/smp.lhco as mysample
set mysample.xsection = 1.23
```
As for the Delphes error you are getting, this generally happens when the ROOT version is not precisely what Delphes wants. I haven't seen any issues in terms of physics when I see this error, but if you like to be on the safe side, I suggest asking Delphes developers.

hope it helps
cheers

**Comment by jackaraz** [comment]
I'm assuming this issue has been resolved, closing the issue. Please don't hesitate to reopen it if the problem continues.
