### ISSUE TITLE
Histograms for more than one photon

### ISSUE THREAD

**Issue by Karabo-Mosala** [MadAnalysis/madanalysis5#169]
Hi,

I was trying to plot distributions for reconstructed events using lhco file for a process which has 2 photons decayed from a BSM particle. 

plot N(a)
plot PT(a[1])
plot PT(a[2])

 I am getting distributions only for one photon a[1].

Thanks

**Comment by jackaraz** [comment]
Hi @Karabo-Mosala, there is absolutely no way we can know whats going on with your session if you dont provide more information. We need versions of all the related packages that you are using, your OS and **maximum of 10 events** to see if there is indeed a missing information

**Comment by Karabo-Mosala** [comment]
#  typ      eta      phi      pt    jmas   ntrk   btag  had/em   dum1   dum2
   0             1        0
   1    4    1.375   -0.411  221.83    4.31    0.0    0.0    0.00    0.0    0.0
   2    4    2.665   -2.315   89.72   14.99   16.0    0.0    0.00    0.0    0.0
   3    4    3.339   -2.279   33.99    6.55    9.0    0.0    0.02    0.0    0.0
   4    4    4.303   -2.558   33.17    6.05    7.0    0.0    0.62    0.0    0.0
   5    4    2.977   -1.661   12.71    2.35    4.0    0.0    0.07    0.0    0.0
   6    4    3.957   -2.666    6.31    2.64    7.0    0.0  999.90    0.0    0.0
   7    4    2.526   -2.772    5.57    1.35   12.0    0.0    0.00    0.0    0.0
   8    4    4.074   -1.957    3.36    0.42    3.0    0.0    1.94    0.0    0.0
   9    4    3.044    1.386    3.10    1.43    3.0    0.0    0.17    0.0    0.0
  10    6    0.000    1.920  227.31    0.00    0.0    0.0    0.00    0.0    0.0

Packages:
1. Pythia-pgs
2. Delphes-3.5.0


OS: Ubuntu 18

**Comment by Karabo-Mosala** [comment]
#  typ      eta      phi      pt    jmas   ntrk   btag  had/em   dum1   dum2
   0             1        0
   1    4    1.375   -0.411  221.83    4.31    0.0    0.0    0.00    0.0    0.0
   2    4    2.665   -2.315   89.72   14.99   16.0    0.0    0.00    0.0    0.0
   3    4    3.339   -2.279   33.99    6.55    9.0    0.0    0.02    0.0    0.0
   4    4    4.303   -2.558   33.17    6.05    7.0    0.0    0.62    0.0    0.0
   5    4    2.977   -1.661   12.71    2.35    4.0    0.0    0.07    0.0    0.0
   6    4    3.957   -2.666    6.31    2.64    7.0    0.0  999.90    0.0    0.0
   7    4    2.526   -2.772    5.57    1.35   12.0    0.0    0.00    0.0    0.0
   8    4    4.074   -1.957    3.36    0.42    3.0    0.0    1.94    0.0    0.0
   9    4    3.044    1.386    3.10    1.43    3.0    0.0    0.17    0.0    0.0
  10    6    0.000    1.920  227.31    0.00    0.0    0.0    0.00    0.0    0.0

Packages:
1. Pythia-pgs
2. Delphes-3.5.0


OS: Ubuntu 18

**Comment by BFuks** [comment]
Hi,

Do you mind writing **full sentences**, so that we could understand what you are doing, how you are doing it, and what precisely fail? Without this, there is way for us to help you. Also, please provide **complete** event files, with 10 events.

Regards,

Benjamin

**Comment by jackaraz** [comment]
Hi @Karabo-Mosala, by just reading your file myself, the only particles I see are jets, electrons and missing energy. I don't see anything else in your file (the second block, `typ=0`, means photon in LHCO format, assuming that your file follows the standard conventions). So I don't expect Ma5 to generate any photon distribution from this file.

**Comment by Karabo-Mosala** [comment]
Hi,

Thank you very much for help. So it is like problem is arising at Delphes level. 


Thanks again
