### ISSUE TITLE
MadAnalysis5 and delphes level

### ISSUE THREAD

**Issue by Es-said** [MadAnalysis/madanalysis5#172]
### Question

Dear MA5 teams,
i generate e- a > t~ b ve , (t > w+ b, w- > j j ) in Standard model, at delphes level i don't which delphes_card available for e- a collider, i try with ILD, LHeC and FCChe cards but in the event.lhco.gz i found 1 events while the number of events that i generate is 100k. if you have any suggetion about that plz help me?
thank you.

regard,
Es-said Ghourmin

**Comment by BFuks** [comment]
Dear Es-Said,

We have no suggestion, except maybe to contact the Delphes authors (as this seems to be a Delphes issue).

Best regards,

Benjamin

**Comment by Es-said** [comment]
okey, thank you very much
