### ISSUE TITLE
DJR plots for W + jets sample

### ISSUE THREAD

**Issue by Es-said** [MadAnalysis/madanalysis5#175]
### Question

Dear MadAnalysis team,
i have SM background
generate e+ e-  > w+ j j @ 2 
add process e+ e- > w- j j j @ 3
i want to check GJR, i have followed the method available in MadAnalysis  i find in djr plot there only the 0-jet and others N-jet are appear in the figures. i'm confused on that. is there any suggetion? 
 thank you very much 

regard 
Es-said

**Comment by Es-said** [comment]
sorry, the others N-jet not appears in the plot

**Comment by jackaraz** [comment]
Hi @Es-said the [tutorial that you mentioned](https://madanalysis.irmp.ucl.ac.be/raw-attachment/wiki/tutorials/NormalMode-Tuto4.pdf) starts from zero jets, not from two jets. As far as I know (@BenjaminFuks, please confirm), the algorithm assumes that you have the entire spectrum, not just a subset of it.

**Comment by BFuks** [comment]
Yes it does.

Cheers,

Benjamin

**Comment by Es-said** [comment]
thank you for your reply @jackaraz  ,@BFuks 
  generate e+ e- > w+ @ 0 is not possible due  the charge electric not conserved, that why i start in two jet

**Comment by jackaraz** [comment]
Hi @Es-said have you tried to use decay products of W instead of W itself? That way you have W as an off-shell which can produce 2 > 2 amplitude.

**Comment by Es-said** [comment]
i have not tried, do you think what you suggest agree with my phase space which is 2b + 1-lepton + 2j + E_miss

**Comment by jackaraz** [comment]
Hi @Es-said, implement whatever FS you are looking for it's **your** research...

**Comment by Es-said** [comment]
thank you very much
