### ISSUE TITLE
Can't submit the output

### ISSUE THREAD

**Issue by Carlesmer** [MadAnalysis/madanalysis5#177]
### Question

I have set the main.graphic_render = matplotlib, and when I tried to submit the operation I got this error message:
impossible to compile the project. I have attached the compilation.log file. 
Thank you.  

[compilation.log](https://github.com/MadAnalysis/madanalysis5/files/10721786/compilation.log)

**Comment by jackaraz** [comment]
Hi @Carlesmer your root installation requires `c++17` but MadAnalysis is not designed to support `c++17` yet. Can you please deactivate root and try again?

**Comment by jackaraz** [comment]
Hi @Carlesmer please see
https://github.com/MadAnalysis/madanalysis5/blob/65d4239137b5c5e1b6354a4013c36eec4cbf1957/madanalysis/input/installation_options.dat#L10-L12

**Comment by Carlesmer** [comment]
I checked the file and it is (root_veto     = 0 # 0=No, 1=Yes),  I changed it to 1, the MA5 worked perfectly with matplotlib. Thank you so much for all the help.
