### ISSUE TITLE
Plotting variables between one intermediate and one final state particle

### ISSUE THREAD

**Issue by sbphysics** [MadAnalysis/madanalysis5#178]
### Question

Hi,
I am new to Madanalysis. I have generated a process where I have one intermediate particle which is decaying to some other final state particles. I am facing a problem while trying to plot any variable (e.g., DELTAR, sdTHETA etc) between the intermediate particle and one of the final state particles. I am getting a blank plot even after using "[interstate]" as statuscode as one of the particle is final state. What will be the syntax to obtain such a plot? Can I find it anywhere? Any help is appreciated.

Thanks in advance.
SB

**Comment by jackaraz** [comment]
Hi @sbphysics , assuming you are not using reco mode, what you are doing is correct. However, generators only write onshell particles into the output file so you need to make sure that your particle is onshell if its not written in the file ma5 can not know that it exists.

**Comment by jackaraz** [comment]
Due to a lack of activity, I assume this issue has been resolved. Please feel free to reopen if you need to.

**Comment by sbphysics** [comment]
Thank you for your suggestion. In Madanalysis, how can I denote that my interstate particle is onshell? Can I reconstruct the pT of this interstate particle or vectorially sum the pTs of its decaying products?

**Comment by jackaraz** [comment]
Hi @sbphysics, madanalysis is not an event generator; you can not set event-level information. This can only be done in madgraph by setting breit wigner width and enforcing the interstate particles. If a particle is onshell it will be written in lhe/hepmc file and madanalysis will be able to read it.

**Comment by sbphysics** [comment]
Thank you. I understand. I had defined width of the interstate particle in
Madgraph. But still I am getting the above plot blank.

Another problem was regarding vectorial sum of transverse momenta of two
final state particle and one intermediate particle. I am unable to do it
using momentum_Pt(). Is it wrong?

Thanks in advance.
SB
