### ISSUE TITLE
ma5 python file in bin is not executing

### ISSUE THREAD

**Issue by sandeepts224** [MadAnalysis/madanalysis5#18]
### Question

When I am trying to use madanlysis5. But it is not executing. When I type ./bin/ma5 it is saying that a file or directory like that does not exist. But when I check the file in bin ma5 is exist.

code
sandeep@Sandeep:~/Downloads/MadAnalysis5_v1.9.60/madanalysis5$ ./bin/ma5
/usr/bin/env: ‘python’: No such file or directory
sandeep@Sandeep:~/Downloads/MadAnalysis5_v1.9.60/madanalysis5$

Thanks
Sandeeep

**Comment by jackaraz** [comment]
Hi @sandeepts224 from which directory are you trying to execute ‘ma5’?

**Comment by jackaraz** [comment]
Hi @sandeepts224 sorry I just saw your code it crossed out (would be easier to read if you use markdown syntax). It seems like your python environment has not been built. Your error message says;
```
/usr/bin/env: ‘python’: No such file or directory
```
So the initialization script can not find python it's not related to ma5, please install a global python environment and try again. It is likely that you haven't set up `PYTHONPATH` or `LD_LIBRARY_PATH` in your `.bashrc` properly. You need to include the path of the python executable in `PYTHONPATH` for your machine to globally pick it up.

**Comment by sandeepts224** [comment]
Thanks, It worked
