### ISSUE TITLE
recasting compilation error for some particular analyses

### ISSUE THREAD

**Issue by sihyunjeon** [MadAnalysis/madanalysis5#191]
### System Settings

SLC 7
Python 3.8.11
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
MA : 1.10.9

### Describe the bug

I am doing the following with generated hepmc file after `./bin/ma5 -R` for recasting runs.

`set main.recast = on`
`import PATH/TO/HEPMC`
`submit`

and then I select only cms_exo_20_002 to recast.
This gave me following error

MA5-ERROR: impossible to compile the project. For more details, see the log file:
MA5-ERROR: /data9/Users/shjeon/SummaryPaper/HNL/PPtoTauTauJJ/madanalysis5/ANALYSIS_0_SFSRun/Build/Log/compilation.log
MA5-ERROR: job submission aborted.
MA5-ERROR: job submission aborted.

And if I look at the error log it starts like below

SampleAnalyzer/User/Analyzer/cms_exo_20_002.cpp:8:3: error: 'RecTracks' was not declared in this scope
   RecTracks Tracks = filter(event.rec()->tracks(), 0.5, 5.);
   ^
SampleAnalyzer/User/Analyzer/cms_exo_20_002.cpp:8:13: error: expected ';' before 'Tracks'
   RecTracks Tracks = filter(event.rec()->tracks(), 0.5, 5.);
             ^

Since this failed I tried cms_exo_17_011 and this failed with same error. I had no issue when running recasting that runs on Delphes so I thought it is a problem from SFS PAD not being compiled in my setup. However, atlas_susy_2016_07 ran without an issue.

If I do in my terminal
`grep -r "RecTracks" tools/PADForSFS/Build/SampleAnalyzer/User/Analyzer/*cpp`
only cms_exo_17_011.cpp and cms_exo_20_002.cpp shows up among all cpp files. Also the same for "RecLeptons"
So I wonder if the error is related to this.

### To Reproduce

-

**Comment by BFuks** [comment]
Hi Sihyun,

As indicated on the PAD webpage, you need to use MA5 version 2.0.x for this analysis.

Regards,

Benjamin

**Comment by sihyunjeon** [comment]
Hi @BFuks , is 2.0.x not yet available publicly? current master branch seems to be 1.9

**Comment by jackaraz** [comment]
Hi @sihyunjeon please see the releases not the main branch. Main branch is development branch and the releases are the stable versions after they pass all the tests.

**Comment by sihyunjeon** [comment]
Ah I see sorry for the unnecessary alert!
