### ISSUE TITLE
Number of selected events doesn't match the number of generated events

### ISSUE THREAD

**Issue by mmarko5** [MadAnalysis/madanalysis5#198]
### Question

Dear experts,

I generate the BSM process in Madgraphp p > t t~ vt vt~ QCD==2 NP==2, with a leptoquark as the BSM particle. I request 200k events, and the run goes smoothly. I then plot for example the missing transverse energy in MadAnalysis5. Here comes the problem:
when I impose some selection cuts, I can see the number of accepted and rejected events. However, those numbers are always extremely small compared to the total number of events. For example, if I require: ma5> select MET < 5000, I would expect 200k accepted events, but I only have 0.217 (and 0.0 rejected events). I don't know whether I misunderstood something in how the program works, or if there really is a problem. I would appreciate any help !

Thank you in advance,
Marko

**Comment by BFuks** [comment]
Dear Marko,

Posting your issue twice (once as an issue and once as a discussion) in less than 24hours won’t speed up our answering process, on the contrary. Please remember that we are humans, and that we have all rights to take days off, especially during week-ends and bank holidays. In three words: please be patient.

Regards,

Benjamin

**Comment by mmarko5** [comment]
Sorry, I forgot I had already posted the question. I apologize if it came out out a little agressive.

Best regards
Marko

**Comment by BFuks** [comment]
Dear  Marko,

From the information provided, it is actually impossible to help you very much. We do not know how events were exactly generated in MG5, and which MadAnalysis5 commands have been inputted. Have you tried to plot the MET distribution to check its shape? Does it match your expectation?

Regards,

Benjamin

**Comment by jackaraz** [comment]
Hi @mmarko5 that's your luminosity-weighted event yield, not the MC event count. See section 2 of your report 3rd bullet point. That is your event yields before cuts and then compare that with the section 3 table. They are the same as expected.

**Comment by jackaraz** [comment]
Hi @mmarko5, MC event count has nothing to do with physics. The number of events that you generate is the statistical coverage of your phase space. I can generate ten events or billion events; my cross-section is always the same (except for the error on the cross-section ofc that scales with the number of events generated since fewer events mean less phase space coverage). I suggest reading about MC event generation and understanding how madgraph works.
