### ISSUE TITLE
lxplus computing environment?

### ISSUE THREAD

**Issue by sihyunjeon** [MadAnalysis/madanalysis5#200]
### Question

Hello Benjamin/Jack,

Is there a stable setup environment for lxplus? [1] no longer works.

[1] https://answers.launchpad.net/madanalysis5/+question/696211

**Comment by jackaraz** [comment]
Hi @sihyunjeon I leave this to @BenjaminFuks since I've never used lxplus before.

**Comment by BFuks** [comment]
Hi @sihyunjeon,

I ussed to employ `LCG_87/gcc/4.9.3`, from which I was creating a fresh virtual environment that I then used for MA5:
```python3 -m venv my_env; source my_env/bin/activate; python3 -m pip install scipy click tqdm six jsonschema jsonpatch PyYAML```

I however have not used lxplus for months... Maybe something has changed in the meantime.

Cheers,

Benj

**Comment by sihyunjeon** [comment]
So `LCG_87/gcc/4.9.3` doesn't work, and I did 
`source /cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/setup.sh`
with the python venv commands you gave me and it fails like below.

In the long run, it would be ideal if this can be figured out for LHC/CMS analyzers so that we can support this internally (it's a lot difficult to advocate this within the collaboration if it doesn't work on common computing environment and instead have to rely on individual's personal computing environment)

g++ Root/Test.o  -L/afs/cern.ch/work/s/shjeon/MadAnalysis/madanalysis5-2.0.4_beta/tools/SampleAnalyzer/Lib -L/afs/cern.ch/work/s/shjeon/MadAnalysis/madanalysis5-2.0.4_beta/tools/SampleAnalyzer/ExternalSymLink/Lib -lroot_for_ma5 -L/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc8-opt/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -pthread -lm -ldl -rdynamic -lEG -lcommons_for_ma5 -L/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc8-opt/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -pthread -lm -ldl -rdynamic -lEG -o ../Bin/TestRoot
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_terminate()'
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface9::global_control::active_value(int)'
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_initialize()'
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc8-opt/lib/libImt.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const'
collect2: error: ld returned 1 exit status
make: *** [link] Error 1

**Comment by sihyunjeon** [comment]
I'll close this for now if you don't have solutions at the moment!

**Comment by sihyunjeon** [comment]
Or maybe creating a docker image?
