### ISSUE TITLE
Installing-root problem in MadAnalysis5

### ISSUE THREAD

**Issue by sdf951332** [MadAnalysis/madanalysis5#203]
### Question

**System Settings**

Python 3.10.6
g++ 11.3.0
gcc 11.3.0
ma5 1.10.10 (6/5 update)

I'm installing root in ma5 and stuck by some issues:

MA5: **********************************************************
MA5: Installing root
MA5: **********************************************************
MA5: Detecting a previous installation ...
MA5: => found
MA5: Removing the previous installation ...
MA5-WARNING: Are you sure to remove the directory called '/home/zxiang/Documents/MG5/HEPTools/madanalysis5/madanalysis5/tools/root' ? (Y/N)
Answer: Y
MA5: How many cores would you like to use for the compilation ? default = max = 18
   => Answer: 18
MA5: => Number of cores used for the compilation = 18
MA5: **********************************************************
MA5: Creating a devoted folder ...
MA5: Creating a temporary folder ...
MA5: Downloading the package ...
MA5: - 1/1 https://root.cern.ch/download/root_v6.04.08.source.tar.gz ...
MA5: --> 'root.tar.gz' already exists. Package not downloaded.
MA5: Unpacking the package ...
MA5: Configuring the package ...
MA5: Building the package ...
MA5-ERROR: impossible to build the project. For more details, see the log file:
MA5-ERROR: /home/zxiang/Documents/MG5/HEPTools/madanalysis5/madanalysis5/tools/root/compilation.log
MA5: Installation NOT complete.
MA5: Elapsed time = 3 minutes 59 seconds
MA5: => Status: [FAILURE]
MA5: **********************************************************

Sure that I went through the compilation, and these are what I found in the compilation. Because there are too many scripts here, so I just list the errors as follows:

**error 1**
include/TString.h:261:13: note: candidate: ‘TString::TString(Ssiz_t)’
  261 | explicit TString(Ssiz_t ic); // Suggested capacity
      | ^~~~~~~
/tmp/zxiang/MA5_root/root-6.04.08/core/base/src/TBase64.cxx: In static member function ‘static TString TBase64::Decode(const char*)’:
/tmp/zxiang/MA5_root/root-6.04.08/core/base/src/TBase64.cxx:147:19: error: call of overloaded ‘TString(int&)’ is ambiguous
  147 | TString ret(len);
      | ^

**error 2**
make: *** [Makefile:654: core/base/src/TAttFill.o] Error 1
make: *** [Makefile:654: core/base/src/TAttAxis.o] Error 1
make: *** [Makefile:654: core/base/src/TBenchmark.o] Error 1
make: *** [Makefile:654: core/base/src/TAttPad.o] Error 1
make: *** [Makefile:656: core/utils/src/rootclingTCling.o] Error 1
make: *** [Makefile:654: core/base/src/TAttLine.o] Error 1
make: *** [Makefile:654: core/base/src/TAttMarker.o] Error 1
make: *** [Makefile:654: core/base/src/TAttText.o] Error 1
make: *** [Makefile:654: core/base/src/TBrowser.o] Error 1

**error 3**
config.status: executing test/Makefile commands
/tmp/zxiang/MA5_root/root-6.04.08/interpreter/llvm/src/autoconf/install-sh: /tmp/zxiang/MA5_root/root-6.04.08/interpreter/llvm/src/test/Makefile does not exist.
config.status: executing test/Makefile.tests commands
/tmp/zxiang/MA5_root/root-6.04.08/interpreter/llvm/src/autoconf/install-sh: /tmp/zxiang/MA5_root/root-6.04.08/interpreter/llvm/src/test/Makefile.tests does not exist.

**Comment by jackaraz** [comment]
Hi @sdf951332 have you tried with the latest ma5?

**Comment by sdf951332** [comment]
Hi @jackaraz Yes, I've tried the v1.10.10 but the same problems are happening when installing root in ma5

**Comment by jackaraz** [comment]
Hi @sdf951332, which OS are you using? And did you happen to check if your OS meets all the requirements listed by ROOT? ROOT is a third-party package, so please ensure it meets all the requirements.

**Comment by sdf951332** [comment]
Thank @jackaraz and @BFuks, I checked the README.md and requirement.txt, as well as downloaded and sourced the root/bin/thisroot.sh. Now it works!

**Comment by BFuks** [comment]
Great to see that it is solved.

Cheers,

Benjamin
