### ISSUE TITLE
Error while using DPHI_O_PI for met 

### ISSUE THREAD

**Issue by juhidutta** [MadAnalysis/madanalysis5#206]
### Question

Dear Experts,

I am working in the normal mode using madanalysis-v1.6. 

I am facing an error while using DPHI_0_PI(j[1],met).   
It works correctly while computing the Delta Phi between any objects but only runs into an error with the missing energy. The command prompt did not throw any error while running the script, but it crashes with the following message in the log file

g++ -Wall -O3 -fPIC -I/home/lenovo/madanalysis5/tools/ -I./ -o Main/main.o -c Main/main.cpp
g++ -Wall -O3 -fPIC -I/home/lenovo/madanalysis5/tools/ -I./ -o SampleAnalyzer/User/Analyzer/user.o -c SampleAnalyzer/User/Analyzer/user.cpp
SampleAnalyzer/User/Analyzer/user.cpp: In member function ‘virtual bool MA5::user::Execute(MA5::SampleFormat&, const MA5::EventFormat&)’:
SampleAnalyzer/User/Analyzer/user.cpp:460:8: error: ‘_P_metPTorderingfinalstate’ was not declared in this scope
        _P_metPTorderingfinalstate.push_back(&(event.rec()->MET()));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
SampleAnalyzer/User/Analyzer/user.cpp:460:8: note: suggested alternative: ‘_P_metPTorderingfinalstate_REG_’
        _P_metPTorderingfinalstate.push_back(&(event.rec()->MET()));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
        _P_metPTorderingfinalstate_REG_
Makefile:99: recipe for target 'SampleAnalyzer/User/Analyzer/user.o' failed
make: *** [SampleAnalyzer/User/Analyzer/user.o] Error 1

Could you please kindly let me know how I could resolve this issue? I hope I am using the correct format for the met. 

Thank you,

With best regards,
Juhi

**Comment by jackaraz** [comment]
Hi @juhidutta, MET is **missing transverse energy**. As the name suggests, this is just a measure of energy with the unit of GeV and not a vector. You can only compute the $\Delta\phi$ angle between two vectors.

**Comment by juhidutta** [comment]
Hi Jack,

Thank you for the prompt response.

Is there a way I could the MET vector in the normal mode?

Best regards,
Juhi

**Comment by juhidutta** [comment]
Hi Jack,

Thank you for the prompt response.

Is there a way I could access the MET vector in the normal mode?

Best regards,
Juhi

**Comment by BFuks** [comment]
Hi Juhi,

The command you typed works... with the latest MA5 version. The lower case "met" object is the (vector) missing momentum in the normal mode of the code.

Cheers,

Benjamin

**Comment by juhidutta** [comment]
Hi Sir,

Ok, thank you I will install the latest version and try it out.

With best regards,
Juhi
