### ISSUE TITLE
MadAnalysis5 failed to produce the reconstructed event file for reconstruction 'BasicReco'

### ISSUE THREAD

**Issue by prebello** [MadAnalysis/madanalysis5#207]
### Question

 Dear experts,

I am using the MA5 installed in MG5@aMCNLO 3_5_0 version in MAC OS Big Sur 11.7.3 Intel Core i7 .

Proposed changes in the MA5 launchpad to fix this issue are present in madgraph/interface/common_run_interface.py

Nevertheless, I am still receiving the  error msg "MadAnalysis5 failed to
produce the reconstructed event file for reconstruction 'BasicReco'."

additional information: although the input file is there

-rw-r--r--  1 patriciateles  staff   876M Jun 29 14:46
/Users/patriciateles/TOOLS/MG5_aMC_v3_5_0/MY_THIRD_MG5_RUN/Events/run_01_decayed_1/tag_1_pythia8_events.hepmc.gz

Madanalysis is not accepting it

ma5>import /Users/patriciateles/TOOLS/MG5_aMC_v3_5_0/MY_THIRD_MG5_RUN/Events/run_01_decayed_1/tag_1_pythia8_events.hepmc.gz as reco_events
The dataset '/Users/patriciateles/TOOLS/MG5_aMC_v3_5_0/MY_THIRD_MG5_RUN/Events/run_01_decayed_1/tag_1_pythia8_events.hepmc.gz' has not been found or has an unsupported format.
ma5>set main.outputfile=tag_1_pythia8_BasicReco.lhe.gz
ma5>submit /Users/patriciateles/TOOLS/MG5_aMC_v3_5_0/MY_THIRD_MG5_RUN/MA5_HADRON_ANALYSIS_reco_BasicReco_1
no dataset found; please define a dataset (via the command import).
job submission aborted.

May I kindly ask for your help? Thank you

Regards Patricia

**Comment by jackaraz** [comment]
Hi @prebello first of all we need a bit more information such as the version of ma5 that you are using etc. have you installed zlib? when you run ma5 you should see the following.
```
MA5:      - Zlib                     [OK]
```
In which mode are you running ma5? when you type ``display main`` it will tell you which type of files can be processed.

**Comment by prebello** [comment]
hi @jackaraz, thank you for your prompt reply

the version https://github.com/MadAnalysis/madanalysis5/archive/refs/tags/v1.10.9_beta.tar.gz

in madanalysis5_install.log
MA5:      - Zlib                     [OK]

**Comment by jackaraz** [comment]
Hi @prebello, I don't see any problem in your script or ma5 configuration. I don't really know what is going wrong, I'm afraid; @BFuks do you see anything that I might be missing?
