### ISSUE TITLE
HepMC output from LHE files

### ISSUE THREAD

**Issue by gurpinar** [MadAnalysis/madanalysis5#21]
### Question

Dear MadAnalysis5 developers,

I have LHE files from Madgraph for mass scan analysis. I have properly working setup MadAnalysis 5 and delphe. I want to use MadAnalysis 5 to calculate exclusion limit. How can I get HepMC format using Ptyhia8 hadronization?

I would be very grateful if you could help with this.

Thanks in advance. 
Emine

**Comment by jackaraz** [comment]
hi @gurpinar madgraph is interfaced with pythia 8 which you can install and automatically shower/hadronize your particle level events. However, madgraph is an independent software from madanalysis so please refer to their documentation for details. 

cheers
