### ISSUE TITLE
HT including

### ISSUE THREAD

**Issue by Es-said** [MadAnalysis/madanalysis5#222]
### Question

Dear MA5 team,
during my analysis i am focusing on the final state [\tau \nu \tau \nu +2b ] , i am confused by the HT (scalar sum of transverse momentum of jets) and HT-missing. I mean How i can khow that HT only includes the b-quark and b-antiquark or there are other depedance? 
 I am not sure if HT-missing is the SAME as ET-missing

**Comment by jackaraz** [comment]
Hi @Es-said, if you are looking at the matrix element-level events, your HT will only include b-quarks. Still, if you are looking for showered and hadronised events, your HT will include all the hadronic activity in your event, including the ones generated by the b-quarks. $H_T^{\rm miss}$ is not the same as $E_T^{\rm miss}$. $H_T^{\rm miss}$ includes only the missing energy originating from hadronic activity,  $E_T^{\rm miss}$ is all the missing energy.

**Comment by Es-said** [comment]
Thank you @jackaraz 
then here,  HT can include also hadronic tau-decay object  or include only the ones generated by the b-quarks?

**Comment by jackaraz** [comment]
Hi @Es-said, if you are decaying your tau, then yes, it will.

**Comment by Es-said** [comment]
Thank you @jackaraz
