### ISSUE TITLE
The same delphes gets different root files.

### ISSUE THREAD

**Issue by Infinxe** [MadAnalysis/madanalysis5#224]
### Question

Dear software developer:
**The root file I get when I use delphes to process the hepmc file directly is different from the root file I get by calling delphes to process the hepmc file through [PAD.](http://madanalysis.irmp.ucl.ac.be/wiki/PublicAnalysisDatabase) Their D0 and DZ distributions are different.**

Although Delphes directly simulates LLP, the distribution of DZ and D0 obtained is very beautiful. By calling delphes through PAD, the distribution of DZ and D0 obtained is almost all concentrated near 0 (10^{-9}mm). This is a result that is almost impossible to analyze.

(D0: impact parameter in the tranverse plane wrt the closest approach point DZ: impact parameter in the longitudinal plane wrt the closest approach point)

We are not sure which way to obtain the root file is trustworthy. By the way, is the statement on this page still correct? 
[https://madanalysis.irmp.ucl.ac.be/wiki/MA5LongLivedParticle](url)
Questions about this web page include:
(1) Is there no way for Delphes to correctly simulate LLP(Long Lived Particle) alone? 
(2) Does correct simulation of LLP require a special version of MA5?
Thank you for your reply and we look forward to your help our team solve this problem that has been bothering us for a long time.

System Settings:
Ubuntu 20.04.5 LTS
python version: Python 3.9.13
gcc version: g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
MadAnalysis 5 version: MA5: MA5 release : 1.10.12 [ 2023/09/13 ]
Delphes version: Delphes-3.5.0

**Comment by jackaraz** [comment]
Hi @Infinxe, can you send us a small root file where you see this problem and tell us where to look so that we can see what is wrong? For LLPs, I suggest checking [2112.05163](https://arxiv.org/abs/2112.05163) [hep-ph], the link that you are looking is quite outdated.

> (1) Is there no way for Delphes to correctly simulate LLP(Long Lived Particle) alone?

Delphes uses certain approximations to compute D0 and DZ, as explained in the paper above.

> (2) Does correct simulation of LLP require a special version of MA5?

No, if you follow the paper, I linked you will see that you just need to turn on a switch to simulate LLP. This is a time-consuming computation, so we turn it off by default.

**Comment by Infinxe** [comment]
[RecoEvents_v1x2_delphes_card_cms_exo_16_022.zip](https://github.com/MadAnalysis/madanalysis5/files/13113435/RecoEvents_v1x2_delphes_card_cms_exo_16_022.zip)
[test1024_-4_110.zip](https://github.com/MadAnalysis/madanalysis5/files/13113436/test1024_-4_110.zip)
Dear Madanalysis organizer @jackaraz  :
RecoEvents_v1x2_delphes_card_cms_exo_16_022.root is the root file we output using PAD, test1024_-4_110.root is the root file we output using delphes alone. Both of them use the same delphes card, but their ElectronMA5.D0，ElectronMA5.DZ， MuonMA5.D0，MuonMA5.DZ distributions are different. The root file output by delphes alone seems to be correct, and the distribution of their other kinematic variables is the same.
Thank you for taking the time to help us solve the problem!

**Comment by jackaraz** [comment]
Could you please write how you produce it in detail so I can ensure the procedure is correct?

**Comment by Infinxe** [comment]
The command I asked ma5 to execute is according to this web page：[http://madanalysis.irmp.ucl.ac.be/wiki/PublicAnalysisDatabase](url)
    set main.recast = on
    set main.recast.store_root = True
    set main.recast.card_path = < path-to-a-recasting-card > We used ( cms_exo_16_022                v1.2        on    delphes_card_cms_exo_16_022.tcl                    #  CMS   - 13 TeV - Displaced leptons (2.6/fb) )
    import < path-to-the-event-sample >   ( hepmc file generated by mg5 ) 
    submit
Then in this directory /home/will/Program/madanalysis5main/ANALYSIS_95/Output/SAF/defaultset/RecoEvents/RecoEvents_v1x2_delphes_card_cms_exo_16_022.root, we can get the root file. Its electron D0, DZ distribution is different from that obtained directly with delphes.
Attached are some cards that we use mg5 to generate hepmc files.
Sincerely thank you for your help！
[Cards.zip](https://github.com/MadAnalysis/madanalysis5/files/13116424/Cards.zip)

**Comment by jackaraz** [comment]
How did you use delphes? Have you used the same delphes version that ma5 uses internally?

**Comment by Infinxe** [comment]
Yes, we tried using SFS and it works fine now , thank you very much for helping us !
