### ISSUE TITLE
Unable to create folder for PADForSFS installation.

### ISSUE THREAD

**Issue by theoreticalphysics-cpu** [MadAnalysis/madanalysis5#236]
### Question

I am attempting to install PADForSFS into MadAnalysis. However, my terminal states that I am unable to create a directory. Is this some sort of issue with my folder permissions?

<img width="904" alt="Screen Shot 2024-01-18 at 2 58 00 AM" src="https://github.com/MadAnalysis/madanalysis5/assets/85380045/e7d6ebb2-6240-4284-bc09-ff1896583ceb">

**Comment by BFuks** [comment]
Hi,

There is something wrong with your path. How are you starting MA5? You should be in the main folder and type `./bin/ma5`.

Cheers,

Benjamin

**Comment by theoreticalphysics-cpu** [comment]
I am starting MA5 by navigating to the folder. It is installed in /Users/username/Documents/MG5_aMC_v2_9_17/HEPTools/madanalysis5/madanalysis5/bin. So I navigate using cd Documents, then cd MG5_aMC_v2_9_17, then cd HEPTools, then cd madanalysis5, then cd madanalysis5, then I use the ./bin/ma5 command to start MA5.

**Comment by theoreticalphysics-cpu** [comment]
Also, when I attempt to use the ./bin/ma5 command, this results in the error "zsh: no such file or directory".

**Comment by theoreticalphysics-cpu** [comment]
Update: I resolved the issue after granting Terminal full disk access.
