### ISSUE TITLE
How to select events of interest in reconstruction mode?

### ISSUE THREAD

**Issue by simonp33** [MadAnalysis/madanalysis5#24]
### Question

Hello,

I am stuck at selecting events of interest in reconstruction mode of MadAnalysis5 (MA5).
I studied MA5 manual(MadAnalysis 5 v1.6 Normal-Mode reference card), but i could not find a solution.

What i want to do is to select events satisfying some specific conditions.
Codes i want to run is something like:

  define a = M(mu+[1] mu-[1]) - M(mu+[2] mu-[2])
  define b = M(mu+[1] mu-[2]) - M(mu+[2] mu-[1])
  select a < b
  plot M(mu+[1] mu-[1])
  plot M(mu+[2] mu-[2])

Here, I want to define variable a and b like above at first and then select events that a is smaller than b.
So, my question is that there is any working code similar to above.
I mean is there any 'define' function as above?

I typed commands in MA5 prompt with reconstruction mode and an error occured as below.

  ma5>set main.fastsim.package=delphes
  ma5>set main.fastsim.detector=cms
  ma5>import unweighted_events.lhe.gz
  ma5>define a = m(mu+[1] mu-[1]) - m(mu+[2] mu-[2])
  MA-5 ERROR: cannot import particles in MA5 reconstructed mode

Following are details of the analysis.

  - Event generator: MadGraph5(MG5)
  - Model: DM_simp_s_spin1 # Dark matter Simplified model
  - No. of events: 10,000
  - Dark photon mass: 0.3 GeV
  - MG5 channel: e+ e- > y1 y1 a, y1 > mu+ mu- #y1 is dark photon with spin1
  - MA5 Input file: LHE file generated from MG5
  - MA5 mode: Reconstruction(detector simulation using Delphes) & normal mode (not expert mode)

I really appreciate it if you give me answer .

Sincerely,

Kihong Park

**Comment by jackaraz** [comment]
Hi @simonp33 you can not define variables in normal mode, you will need to use expert mode for this.

**Comment by simonp33** [comment]
Dear Jackaraz, 
Thank you for the answer!
