### ISSUE TITLE
UFO from SARAH and Madanalysis5

### ISSUE THREAD

**Issue by tphyspg** [MadAnalysis/madanalysis5#25]
### Question

Hi,

I have used SARAH 4.14.5 to generate UFO output and extracted spectrum and decay information from SPheno 4.0.4 using the SARAH-SPheno interface. However, Madanalysis5 (downloaded through the latest version of MG) is not working when I tried to work with the SM from SARAH. Any suggestions?

Ubuntu 20.04.3 LTS
Python -v: 3.8.10
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
MA5: MA5 release : 1.9.32 [ 2021/07/16 ]

Best regards,

Pradipta

**Comment by BFuks** [comment]
Hi Pradipta,

Without having more information on what you are doing, I am afraid we cannot answer anything.

Regards,

Benjamin

**Comment by tphyspg** [comment]
Dear Benjamin,

1. Generated UFO and SPheno outputs from SARAH 4.14.5 for the default SM using Mathematica 10. SPheno output was given to SPheno 4.0.4 (with proper flags in the input file, file attached inside SM_inout_SPheno.zip) for generating spectrum and decays (file attached 
[SM_inout_SPheno.zip](https://github.com/MadAnalysis/madanalysis5/files/8038820/SM_inout_SPheno.zip)
inside SM_inout_SPheno.zip)
2. Implemented this UFO to MG5_aMC_v3_3_1 with import model SM-UFO/ -modelname
3. For python 3 compatibility, subsequently did convert model /home/pradipta/HePTools/MG5_aMC_v3_3_1/models/SM-UFO/
4. For a test run, after defining p for this model accordingly, we did "generate p p > u3 u3bar" (t t~ in original notations)
5. On a subsequent output pptt (given name) run we got INFO: Generating MadAnalysis5 default cards tailored to this process 
WARNING: MadAnalysis5 failed to write a parton-level default analysis card for this process. 
WARNING: Therefore, parton-level default analysis with MadAnalysis5 will be empty. 
WARNING: MadAnalysis5 failed to write a hadron-level default analysis card for this process. 
WARNING: Therefore, hadron-level default analysis with MadAnalysis5 will be empty.

Thanks in advance

Best regards,

Pradipta

**Comment by BFuks** [comment]
Dear Pradipta,

Non-standard particle names are used in the SARAH UFO, so that MadAnalysis does not know what to do. Therefore, it prints a few warnings to the screen. 

This only means that you will have to write your cards entirely by yourself. Automated card generation only works if the usual SM particles (with their standard names) are available.

Regards,

Benjamin
