### ISSUE TITLE
NTracks not Set to 0

### ISSUE THREAD

**Issue by Gianco99** [MadAnalysis/madanalysis5#260]
### Feature details

When reading Delphes trees, NTracks is being automatically set to 0 instead to the value in the tree for jets and fatjets.

Jets - https://github.com/MadAnalysis/madanalysis5/blob/6a3ad2e8100bf2e2c03668563297047744ac9ee5/tools/SampleAnalyzer/Interfaces/delphes/DelphesTreeReader.cpp#L590

Fatjets - https://github.com/MadAnalysis/madanalysis5/blob/6a3ad2e8100bf2e2c03668563297047744ac9ee5/tools/SampleAnalyzer/Interfaces/delphes/DelphesTreeReader.cpp#L627

Can these be modified to correctly read the number of constituents in each jet?

### Implementation

`jet->ntracks_  = part->NCharged + part->NNeutrals;`

### How important would you say this feature is?

3: Very important! Blocking work.

### Additional information

My analysis uses track multiplicity as the variable we fit, so this is a must have for other people to reproduce our results through MadAnalysis.

**Comment by jackaraz** [comment]
Hi @Gianco99, In expert mode, you can initialise and set anything you like; that's what it was designed for.

**Comment by Gianco99** [comment]
Ah I understand, I had overlooked how when doing `source setup.sh` prior to compiling the build, we can customize this to point to our own tools/Analyzer, not just the default SampleAnalyzer. I though we were only able to customize the `user.cpp` and `user.h ` equivalents.

Thank you!
