### ISSUE TITLE
software issuse

### ISSUE THREAD

**Issue by samiullah87654321** [MadAnalysis/madanalysis5#263]
![IMG_20241004_154715](https://github.com/user-attachments/assets/af4e7196-50e5-492c-bded-3510bae7205a)

**Comment by BFuks** [comment]
Hello,

Your message and screenshot are unreadable. Do you mind updating them? Thanks in advance.

Benjamin

**Comment by samiullah87654321** [comment]
Ok I try again

**Comment by samiullah87654321** [comment]
plz check now ...i update it

**Comment by samiullah87654321** [comment]
the error is in blue lines

**Comment by BFuks** [comment]
Hi.

That's a Madgraph problem, and not a MadAnalysis 5 problem. I therefore suggest to ask the MG5aMC authors.

Regards,

Benjamin

**Comment by samiullah87654321** [comment]
Ok thank you...would you kindly give me a way to approach madgrahe author
