### ISSUE TITLE
a compilation issue when using the madanalysis5-taco_interface version for recasting

### ISSUE THREAD

**Issue by baozhiyang-hep** [MadAnalysis/madanalysis5#277]
### Question

Hello!
The Delphes version is 3.4.3, and the FastJet version is 3.3.x. The system version, GCC version, and Python version I am using are as follows:

(ma5_taco) tev@alien-14:~/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(ma5_taco) tev@alien-14:~/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface$ python --version
Python 3.8.20
(ma5_taco) tev@alien-14:~/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface$ pwd
/home/tev/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface

I ran `./bin/ma5 -R jiaoben3.sh` under the `madanalysis5-taco_interface` directory, and the content of `jiaoben3.sh` is as follows:

set main.recast = on
set main.merging.check = true
#set main.fastjet.path =/home/tev/Desktop/bzy/combine_test
set main.recast.TACO_output = TACO_output
#set main.recast.TACO_output = /home/tev/Desktop/bzy/combine_testing/madanalysis5-main/madanalysis5-main/recast_corr.dat
#set main.merging.njets = 2
set main.recast.store_root = True
set main.recast.card_path = /home/tev/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface/recasting_card.dat
#set main.fastsim.package  = delphes
import 2024_0727_events.hepmc as SUSY_total
set SUSY_total.xsection = 0.832563338402778
submit recast_test_hepmc_1123_02

The following issue occurred during execution:

MA5:    -> Storing the file '2024_0727_events.hepmc' in the dataset 'SUSY_total'.
MA5: ma5>set SUSY_total.xsection = 0.832563338402778
MA5: ma5>submit recast_test_hepmc_1123_02
MA5:    Creating folder 'recast_test_hepmc_1123_02'...
MA5-WARNING: A directory called '/home/tev/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface/recast_test_hepmc_1123_02' is already defined.
Would you like to remove it ? (Y/N)
Answer: Y
MA5:    Checking the recasting card...
MA5: Would you like to edit the recasting Card ? (Y/N)
Answer: N
MA5:    Getting the list of delphes simulation to be performed...
MA5:    **********************************************************
MA5:                   v1.2+ detector simulations                
MA5:    **********************************************************
MA5:    **********************************************************
MA5:        vSFS running of the PAD on events generated with     
MA5:                 sfs_card_atlas_susy_2018_31.ma5             
MA5:    **********************************************************
MA5: Particle labels from input/reco_default.txt
MA5:   => 14 particles successfully exported.
MA5: Multiparticle labels from madanalysis/input/multiparticles_reco_default.txt
MA5:   => 9 multiparticles successfully exported.
MA5:   => 9 multiparticles successfully exported.
MA5: Executing the commands from the script
MA5: /home/tev/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface/tools/PADForSFS/Input/Cards/sfs_card_atlas_susy_2018_31.ma5...
MA5:    Creating folder 'recast_test_hepmc_1123_02'...
MA5-WARNING: A directory called '/home/tev/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface/recast_test_hepmc_1123_02_SFSRun' is already defined.
Would you like to remove it ? (Y/N)
Answer: Y
MA5:    Copying 'SampleAnalyzer' source files...
MA5:    Writing the list of datasets...
MA5:    Creating Makefiles...
MA5:    Updating the main executable
MA5:    Compiling 'SampleAnalyzer'...
MA5-ERROR: impossible to compile the project. For more details, see the log file:
MA5-ERROR: /home/tev/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface/recast_test_hepmc_1123_02_SFSRun/Build/Log/compilation.log
MA5-ERROR: job submission aborted.
MA5-ERROR: job submission aborted.

The content of the log file `compilation.log` is as follows:

1 c++ -Wall -std=c++11 -O3 -fPIC -I/home/tev/Desktop/bzy/combine_testing/ma5_TACO_interface/madanalysis5-taco_interface/tools/ -I./ -pthread -std=c++11 -m64 -I/home/tev/root/include -o Main/main.o -c Main/main    .cpp$
  2 Main/main.cpp: In function ‘int main(int, char**)’:$
  3 Main/main.cpp:65:38: error: redeclaration of ‘std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > prmatlas_susy_2018_31’$
  4    std::map<std::string, std::string> prmatlas_susy_2018_31;$
  5                                       ^~~~~~~~~~~~~~~~~~~~~$
  6 Main/main.cpp:54:38: note: ‘std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > prmatlas_susy_2018_31’ previously declared here$
  7    std::map<std::string, std::string> prmatlas_susy_2018_31;$
  8                                       ^~~~~~~~~~~~~~~~~~~~~$
  9 Main/main.cpp:66:17: error: redeclaration of ‘MA5::AnalyzerBase* analyzer_atlas_susy_2018_31’$
 10    AnalyzerBase* analyzer_atlas_susy_2018_31=$
 11                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~$
 12 Main/main.cpp:55:17: note: ‘MA5::AnalyzerBase* analyzer_atlas_susy_2018_31’ previously declared here$
 13    AnalyzerBase* analyzer_atlas_susy_2018_31=$
 14                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~$
 15 Main/main.cpp:71:15: error: redeclaration of ‘MA5::WriterBase* writer1’$
 16    WriterBase* writer1 =$
 17                ^~~~~~~$
 18 Main/main.cpp:60:15: note: ‘MA5::WriterBase* writer1’ previously declared here$
 19    WriterBase* writer1 =$
 20                ^~~~~~~$
 21 Main/main.cpp:141:12: error: ‘analyzer2’ was not declared in this scope$
 22        if (!analyzer2->Execute(mySample,myEvent)) continue;$
 23             ^~~~~~~~~$
 24 Makefile:101: recipe for target 'Main/main.o' failed$
 25 make: *** [Main/main.o] Error 1$

It seems that I cannot resolve the issue by directly modifying `main.cpp`, because this file gets regenerated during repeated compilations. Could you please advise on how to resolve this issue?

**Comment by BFuks** [comment]
Hi,

Can you please try without `set main.merging.check = true`. If this does not work, I would need a test sample with 10 events, as well as the recasting card.

Regards,

Benjamin

**Comment by baozhiyang-hep** [comment]
After eliminating the line "set main.merging.check = true", the previous problem eliminate. Thanks a lot for your kind reply!

Sincerely yours,
Zhiyang Bao
