### ISSUE TITLE
root and delphes installation

### ISSUE THREAD

**Issue by shubhani16** [MadAnalysis/madanalysis5#30]
### Question

Hi

I am trying to install delphes from MA5 command line. I am using modules :

1) python/2.7.14
2) gcc/6.4.0, I have tried using latest versions as well for example gcc/10.3.0
3)root/6.24.06

Before installing delphes , root works fine with MA5:
 **********************************************************
MA5: Component 8/11 - library: interface to Root
MA5: - Cleaning the project before building the library ...
MA5: - Compiling the source files ...
MA5: - Linking the library ...
MA5: - Checking that the library is properly built ...
MA5: - Cleaning the project after building the library ...
MA5: => Status: [OK]
MA5: **********************************************************
MA5: Component 9/11 - test program: interface to Root
MA5: - Cleaning the project before building the test program ...
MA5: - Compiling the source files ...
MA5: - Linking the test program ...
MA5: - Checking that the test program is properly built ...
MA5: - Cleaning the project after building the test program ...
MA5: - Running the test program ...
MA5: - Checking the program output...
MA5: => Status: [OK]

But when I try to install the delphes it stops with an error, this is the delphes compilation log:

  GNU nano 2.3.1 File: compilation.log

In file included from /mainfs/local/software/gcc/10.3.0/include/c++/10.3.0/memory:83,
                 from /local/software/cern/ROOT_6.24.06/install/include/ROOT/TypeTraits.hxx:15,
                 from /local/software/cern/ROOT_6.24.06/install/include/TString.h:30,
                 from /local/software/cern/ROOT_6.24.06/install/include/TNamed.h:26,
                 from /local/software/cern/ROOT_6.24.06/install/include/TFormula.h:15,
                 from /local/software/cern/ROOT_6.24.06/install/include/TF1.h:29,
                 from /local/software/cern/ROOT_6.24.06/install/include/TF2.h:26,
                 from ./classes/DelphesTF2.h:22,
                 from classes/DelphesTF2.cc:19:
/mainfs/local/software/gcc/10.3.0/include/c++/10.3.0/bits/unique_ptr.h:395:7: note: candidate: 'std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = TFormula; _Dp =$
  395 | operator=(nullptr_t) noexcept
      | ^~~~~~~~
/mainfs/local/software/gcc/10.3.0/include/c++/10.3.0/bits/unique_ptr.h:395:17: note: no known conversion for argument 1 from 'TFormula*' to 'std::nullptr_t'
  395 | operator=(nullptr_t) noexcept
      | ^~~~~~~~~
>> Compiling modules/EnergySmearing.cc
make: *** [tmp/classes/DelphesTF2.o] Error 1
make: *** Waiting for unfinished jobs....
>> Compiling modules/ExampleModule.cc
modules/DualReadoutCalorimeter.cc: In member function 'virtual void DualReadoutCalorimeter::Process()':
modules/DualReadoutCalorimeter.cc:225:12: warning: unused variable 'ecalSigma' [-Wunused-variable]
  225 | Double_t ecalSigma, hcalSigma, sigma;
      | ^~~~~~~~~
modules/DualReadoutCalorimeter.cc:225:23: warning: unused variable 'hcalSigma' [-Wunused-variable]
  225 | Double_t ecalSigma, hcalSigma, sigma;
      | ^~~~~~~~~
modules/DualReadoutCalorimeter.cc: In member function 'void DualReadoutCalorimeter::FinalizeTower()':
modules/DualReadoutCalorimeter.cc:510:12: warning: unused variable 'ecalNeutralEnergy' [-Wunused-variable]
  510 | Double_t ecalNeutralEnergy, hcalNeutralEnergy, neutralEnergy;
      | ^~~~~~~~~~~~~~~~~
modules/DualReadoutCalorimeter.cc:510:31: warning: unused variable 'hcalNeutralEnergy' [-Wunused-variable]
  510 | Double_t ecalNeutralEnergy, hcalNeutralEnergy, neutralEnergy;
      | ^~~~~~~~~~~~~~~~~
modules/DualReadoutCalorimeter.cc:513:12: warning: unused variable 'ecalNeutralSigma' [-Wunused-variable]
  513 | Double_t ecalNeutralSigma, hcalNeutralSigma, neutralSigma;
      | ^~~~~~~~~~~~~~~~
modules/DualReadoutCalorimeter.cc:513:30: warning: unused variable 'hcalNeutralSigma' [-Wunused-variable]
  513 | Double_t ecalNeutralSigma, hcalNeutralSigma, neutralSigma;
      | ^~~~~~~~~~~~~~~~
external/Hector/H_BeamParticle.cc: In member function 'void H_BeamParticle::computePath(const H_AbstractBeamLine*, bool)':
external/Hector/H_BeamParticle.cc:483:25: warning: variable 'temp_s' set but not used [-Wunused-but-set-variable]
  483 | double temp_x, temp_y, temp_s, temp_tx, temp_ty;
      | ^~~~~~
external/Hector/H_BeamParticle.cc: In member function 'void H_BeamParticle::computePath(const H_AbstractBeamLine&, bool)':
external/Hector/H_BeamParticle.cc:533:25: warning: variable 'temp_s' set but not used [-Wunused-but-set-variable]
  533 | double temp_x, temp_y, temp_s, temp_tx, temp_ty;

If I go and check the tools directory delphes is present there. On the other hand if I now try to open MA5 it stops with there error:

Traceback (most recent call last):
  File "./bin/ma5", line 70, in <module>
    madanalysis.core.launcher.LaunchMA5(version, date, ma5dir)
  File "/mainfs/scratch/sj1n19/MG5/MG5_aMC_v2_7_2/HEPTools/madanalysis5/madanalysis5/madanalysis/core/launcher.py", line 411, in LaunchMA5
    repeat = MainSession(mode,arglist,ma5dir,version,date)
  File "/mainfs/scratch/sj1n19/MG5/MG5_aMC_v2_7_2/HEPTools/madanalysis5/madanalysis5/madanalysis/core/launcher.py", line 260, in MainSession
    if not main.CheckConfig(debug=mode.debug):
  File "/mainfs/scratch/sj1n19/MG5/MG5_aMC_v2_7_2/HEPTools/madanalysis5/madanalysis5/madanalysis/core/main.py", line 438, in CheckConfig
    if not checkup.CheckOptionalProcessingPackages():
  File "/mainfs/scratch/sj1n19/MG5/MG5_aMC_v2_7_2/HEPTools/madanalysis5/madanalysis5/madanalysis/system/checkup.py", line 326, in CheckOptionalProcessingPackages
    self.archi_info.has_delphes = checker2.checkDelphes()
  File "/mainfs/scratch/sj1n19/MG5/MG5_aMC_v2_7_2/HEPTools/madanalysis5/madanalysis5/madanalysis/system/config_checker.py", line 455, in checkDelphes
    self.archi_info.delphes_lib=os.path.normpath(myfiles[0])
IndexError: list index out of range

Is it due to the version of packages I am using where MA5 is not able to build the suitable environment ? I am using MA5 release : 1.8.45.

Any help would be much appreciated.

Thanks
Shubhani

**Comment by jackaraz** [comment]
Hi @shubhani16 could you please try with the [latest version of MadAnalysis](https://github.com/MadAnalysis/madanalysis5/releases).

**Comment by shubhani16** [comment]
Hi Jack 

Yes I can try the new version, what are the python and gcc version that needs to be used?

Regards
Shubhani

**Comment by jackaraz** [comment]
> Hi Jack
> 
> Yes I can try the new version, what are the python and gcc version that needs to be used?
> 
> Regards Shubhani

You can find the details about the requirements [here](https://github.com/MadAnalysis/madanalysis5#requirements).

**Comment by shubhani16** [comment]
Thanks Jack.

Just one question is the latest version can be downloaded using Madgraph?

I am explicilty loading python/3.9.7 for the latest ma5 version, but this warning is being shown:
MA5: Checking mandatory packages:
MA5-WARNING: Python version 2.7.5 detected.
MA5-WARNING: Python 2 functionality is deprecated, and will no longer be supported in a close future.

**Comment by jackaraz** [comment]
hi @shubhani16 latest version of MadGraph should be able to download ma5 v1.9.60. Please make sure that python libraries are properly declared in `PYTHONPATH`. you can find the declaration in `.bashrc`. Ma5, by default, uses python module within `/usr/bin/env`. Note that ma5 haven't been tested with python 3.9, but only 3.8.

**Comment by shubhani16** [comment]
Hi Jack

I got both madgraph and MA5 working with python8. Thanks for the help.

Regards
Shubhani
