### ISSUE TITLE
Luminosity

### ISSUE THREAD

**Issue by GHOUAID** [MadAnalysis/madanalysis5#38]
### Question

Hi,
i use MA5 version 2-8-3, when i set lumi = XXX , XXX any value not affect and i get same result in the S vs B, there is no change in table when luminosity change, i don't know where the problem comes. any comment?

**Comment by jackaraz** [comment]
Hi, MadAnalysis does not have v2.8.3.

**Comment by GHOUAID** [comment]
i have tested also MA5 v 2-9-2  but i have some problem ?

**Comment by GHOUAID** [comment]
anyway, my  problem is  when i set lumi = XXX , XXX any value not affect and i get same result in the S vs B, there is no change in table when luminosity change, i don't know where the problem comes. any comment?

**Comment by jackaraz** [comment]
There is no `set lumi` command. Also, luminosity can not be set via comma separated inputs. You can only set lumi as follows
```
set main.lumi = 123
```
But the main issue here is you are not using MadAnalysis because the latest MadAnalysis version is v1.9.60. I suggest checking which software you are using first. Also reading documentation would help as well.

**Comment by GHOUAID** [comment]
yes, i set it via this cammand that you sign above, but  S vs B was the same even different luminosity value

**Comment by GHOUAID** [comment]
i use this MA5
version = "1.8.45"
date = "2020/05/01"
last version that i share with you is MG5 version.

**Comment by jackaraz** [comment]
MadAnalysis and MadGraph are different software. I suggest calculating your signal and background by hand first and making sure that how they need to change with luminosity. then you can form a *detailed* question including your hand calculation compared with MadAnalysis calculation. Until then there is no information in this question that I can help with.

Also, v1.8.45 is quite old, I suggest updating your MadAnalysis.

**Comment by GHOUAID** [comment]
please, what i wander to know is when luminosity change via set main.lumi will change number of S vs B? i also want to know xsect after cut but change luminosity doesn't affect ?

**Comment by jackaraz** [comment]
As I said a hand calculation will show you what needs to change.

**Comment by GHOUAID** [comment]
more explain please, cuz i don't understand much how i can do that by hand?

**Comment by GHOUAID** [comment]
more information
without set main.lumi command 
sum of weight of signal 6.192608e-04
sum of weight of background 3.63e-03
S vs B  0.0094

**Comment by jackaraz** [comment]
Great now could please you calculate number of events for signal and background separately with 10 fb^-1 luminosity.


--
Jack Y. Araz

**Comment by GHOUAID** [comment]
thank you so much,
what if i want xsect after cut. How i can get it?

**Comment by jackaraz** [comment]
By multiplying initial xsec with final cut efficiency.

**Comment by GHOUAID** [comment]
thank you so much

**Comment by GHOUAID** [comment]
Hi jack,
i still have one question, what if i want plot d sigma /d Pt (pb/GeV) in my y-axis?

**Comment by jackaraz** [comment]
Check the [FAQ please](https://github.com/MadAnalysis/madanalysis5)
