### ISSUE TITLE
Using MadAnalysis 5 for reinterpreting LHC results

### ISSUE THREAD

**Issue by Revue-Starlight-Topstar** [MadAnalysis/madanalysis5#45]
### Question

Dear Madanalysis team,
I sincerely ask you that in the reconstructed-level mode, I get the output of the automatic recasting procedure of MadAnalysis 5(CLs_output_summary.dat), but how to know whether the input model points are excluded or allowed, just like the results given by CheckMate?
I am a beginner. I would appreciate it if you could answer my question.

System Settings:
Operating system:  16.04.1-Ubuntu 
Python version:  Python 3.5.2
gcc/c++ version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
MadAnalysis 5 version: 1.9.60

**Comment by jackaraz** [comment]
Hi @Revue-Starlight-Topstar this depends on at what confidence level you would like to exclude your model. e.g. in particle physics we usually choose 95% CL to say that our sample is excluded. This value is given in your `CLs_output.dat` file in `1-cls` block. If that value for the **best signal region** is greater than or equal to 0.95 then your sample is excluded.

**Comment by Revue-Starlight-Topstar** [comment]
Dear Jack,
When I want to add a specific cross-sectional value in the reconstructed-level mode, I'm not sure what the specific unit of value is. It may be Fb or Pb?And there is no information about the cross section in the generated file (defaultset.saf).

history.ma5
set main.recast = on
import <path-to-events.hepmc.gz>
set main.recast.card_path =  <path-to-a-recasting-card>
set defaultset.xsection = 1.8718e-08
submit

**Comment by jackaraz** [comment]
Hi @Revue-Starlight-Topstar cross section is always assumed to be in pb. Please see the relevant papers (1407.3278, 1910.11418) and manual, all the information that you need is provided there. Additionally we have tutorials and talks that you can see as well. All the links are available in the [Readme file](https://github.com/MadAnalysis/madanalysis5). `defaultset.saf` File only includes the cross section information provided in the sample file which in your case Im assuming that you are using a recast based on Delphes, Root file does not include cross section information hence the corresponding columns are zero.

**Comment by Revue-Starlight-Topstar** [comment]
Dear Jack,
Your patient and meticulous answers have helped me a lot. Thank you very much!

**Comment by jackaraz** [comment]
Hi @Revue-Starlight-Topstar my pleasure
