### ISSUE TITLE
Cross sections in expert mode 

### ISSUE THREAD

**Issue by shubhani16** [MadAnalysis/madanalysis5#46]
### Question

Hi

I am a little confused as to how the Madanalysis 5 is interpreting the cross-section at the expert level. The cross- section I get for my events from madgraph is:
 0.6298 pb
But when I check that in .saf files it has been scaled to 6.298009e+04.
What could be the reason behind it as I have never faced such problems with the older version of MA5.
What is the unit that MA5 will use in .saf files? 

Any help would be much appreciated.

Thanks
Shubhani

**Comment by jackaraz** [comment]
Hi @shubhani16, the expert mode does not use any cross-section value it simply reads the input files and fill cutflows and histograms with the information provided in the event file. If you are looking at the cutflows or histogram files, the presented values are the sum of event weights only. In the sample summary file you can find the information about total xsec, the sum of weights etc **but** this value is reported assuming that the nominal cross-section value in the event file is given as the first value of the cross-section block. Note that some generators do not obey this assumption so it can be generator dependent. In any case, the expert mode does not take into account the cross-section value of your sample in any calculation; hence it is up to you to use any value that you see fit.

**Comment by jackaraz** [comment]
Hi @shubhani16, in expert mode, you calculate it by yourself. That's why it's called "expert" mode. Ma5 outputs only contain the values that you need to use to calculate everything. You can check [`ma5_expert`](https://github.com/MadAnalysis/ma5_expert) plug-in for a python based interpreter.

**Comment by jackaraz** [comment]
> No, I get that what I meant that are there any variables available to use just to grab the cross-section. 

Depends on your generator. If the generator follows the convention that I mentioned before, there is a main SAF file named after your sample, which should include the **total** cross section value (if you are not using ROOT output, ROOT does not contain any information regarding the cross section hence it will be zero.) If you are looking for the cross section values after each cut, you need to calculate that using the initial xsec value. All the information for calculating cross section/number of events per cut is given in the output files thats how `ma5_expert` calculates everything: simply reads the cutflow and calculates the number of events using the xsec and luminosity value that you have provided.

**Comment by jackaraz** [comment]
Hi @shubhani16 ah I thought you were using cutflow backend, okay for histogram it is exactly like cutflows; each bin contains sum of event weights that falls into that particular bin from there you can caluclate the fraction of the events filling that bin and multiply with xsec to get the xsec per bin. But If I were you, for this specific construction I would just implement this as a cut in two different signal regions this way ma5 will automatically give you two different SAF files for each condition.

**Comment by shubhani16** [comment]
Thanks Jack, I will try to use two separate regions to get the output.
