### ISSUE TITLE
Issue with MadAnalysis5

### ISSUE THREAD

**Issue by sragons2** [MadAnalysis/madanalysis5#47]
Hi,

I have a problem with Madanalysis5.
I use Ubuntu 20.04 LTS.

When I want to use the program, after I launch it with the ./bin/ma5 command, it asks me how many cores I want to use.
Whaever the answer I enter, it starts a compilation process and then
 
I get an error. Here is the report associated with the error : 

make : /home/sofia/madanalysis/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config : commande introuvable
g++ -Wall -O3 -fPIC -I/home/sofia/madanalysis/tools/ -o root/TreeReaderBase.o -c root/TreeReaderBase.cpp
make : /home/sofia/madanalysis/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config : commande introuvable
g++ -Wall -O3 -fPIC -I/home/sofia/madanalysis/tools/ -o root/RootMainHeaders.o -c root/RootMainHeaders.cpp
make : /home/sofia/madanalysis/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config : commande introuvable
g++ -Wall -O3 -fPIC -I/home/sofia/madanalysis/tools/ -o root/ROOTReader.o -c root/ROOTReader.cpp
root/TreeReaderBase.cpp:26:10: fatal error: TChain.h: Aucun fichier ou dossier de ce type
   26 | #include <TChain.h>
      | ^~~~~~~~~~
compilation terminated.
make: *** [Makefile_root:90 : root/TreeReaderBase.o] Erreur 1
make: *** Attente des tâches non terminées....
In file included from root/RootMainHeaders.cpp:26:
/home/sofia/madanalysis/tools/SampleAnalyzer/Interfaces/root/RootMainHeaders.h:30:10: fatal error: TROOT.h: Aucun fichier ou dossier de ce type
   30 | #include <TROOT.h>
      | ^~~~~~~~~
compilation terminated.
make: *** [Makefile_root:90 : root/RootMainHeaders.o] Erreur 1
root/ROOTReader.cpp:29:10: fatal error: TROOT.h: Aucun fichier ou dossier de ce type
   29 | #include <TROOT.h>
      | ^~~~~~~~~
compilation terminated.
make: *** [Makefile_root:90 : root/ROOTReader.o] Erreur 1

(by the way, In this generated error report," commande introuvable" means command not found and "aucun fichier ou dossier de ce type" means no such file/folder found. )

From what I understand, this may be an issue with ROOT.
Does anyone have an idea of how I Could fix the issue ?
Maybe I could disable ROOT, but how to do it, exactly ?

Thanks in advance for your help.

Sofia

**Comment by jackaraz** [comment]
Hi Sofia, from the errors I see that there is a version of root available in your machine and ma5 is trying to access that but seems like either this is an older version of root or a non-complete installation since header files can not be found. By using the file below
https://github.com/MadAnalysis/madanalysis5/blob/e182e79755ba4cb5c8c6d3cc32a9020286f508e6/madanalysis/input/installation_options.dat#L10-L12
you can disable ROOT and reinstall it (if you need it, only delphes package requires ROOT rest of ma5 will work without it) through ma5 or by hand.

**Comment by sragons2** [comment]
Hi Jack,

Thanks a lot for your assistance, I really appreciate it !
I understand your advice, but to be honest I'm not familiar with Ubuntu (I've been using Ubuntu only for a few days).

When you say that I can disable ROOT and reinstall it, would it be possible just to disable it in Ma5, but not uninstall the whole program please ? Because I need it for other programs, and I would prefer avoid to uninstall it.

What should I do with the lines that you gave me please ?
I suppose that I should copy them somewhere, but where exactly ?

Thanks a lot, and sorry for my newbie questions...

**Comment by jackaraz** [comment]
Hi Sofia, the portion of the script that I sent you is available in your local ma5 installation. I just moved it here to show you the location. If you veto root from there, ma5 will not see the root in your system anymore, and you can install a local root just for ma5 to see; the rest of your machine does not need to know it's there. The only thing that you need to do is to change [L11 in this file](https://github.com/MadAnalysis/madanalysis5/blob/e182e79755ba4cb5c8c6d3cc32a9020286f508e6/madanalysis/input/installation_options.dat#L11) as follows
```
root_veto = 1
```
Then ma5 will be compiled without root. Ma5 is capable of installing root automatically given that your system satisfies the requirements for root; you can simply type
```
ma5> install root
```
during a MadAnalysis session. Please see the manual for details.

**Comment by sragons2** [comment]
Hi Jack, thanks a lot for your help !
I will try your solution and let you know if that worked :)

**Comment by BFuks** [comment]
As there is no more comment from the op for about a month, I assume that this thread can be closed. Please re-open it if needed.
