### ISSUE TITLE
Negative values for bounds in SFS are not recognised

### ISSUE THREAD

**Issue by jackaraz** [MadAnalysis/madanalysis5#52]
### System Settings

**System settings:**
* OS: macOS 12.3
* Python version 3.8.9
* gcc/c++ version Apple clang version 13.1.6 (clang-1316.0.21.2)
* MA5: MA5 release : 1.10.2 [ 2022/02/15 ]
* FastJet 3.3.3

### Describe the bug

Negative values in SFS bound declaration are not recognized.

### To Reproduce

```
./bin/ma5 -R
set main.fastsim.package = fastjet
define reco_efficiency mu 0.9 [ eta < -1 ]
```
Error message:
```
MA5-ERROR: Incorrect formula (ignoring the line): [LEAF[ ETA: { id:0 }], OP[ -: { id:2 }]]
MA5: ast nr. 0
MA5: leaves = 4
MA5:   ** Leaf nr. 0
MA5:     -> type/name = var (ETA)
MA5:     -> mother: []
MA5:     -> daugthers: []
MA5:   ** Leaf nr. 1
MA5:     -> type/name = bin1_op (<)
MA5:     -> mother: [2]
MA5:     -> daugthers: []
MA5:   ** Leaf nr. 2
MA5:     -> type/name = bin1_op (-)
MA5:     -> mother: []
MA5:     -> daugthers: [1, 3]
MA5:   ** Leaf nr. 3
MA5:     -> type/name = cst (1)
MA5:     -> mother: [2]
MA5:     -> daugthers: []
```

### Expected behaviour

`-1` Should have been registered as a constant instead of a binary operator.

**Comment by BFuks** [comment]
This bug has been fixed. Review required (#64)
