### ISSUE TITLE
Histogram problem in MA5 expert 

### ISSUE THREAD

**Issue by GHOUAID** [MadAnalysis/madanalysis5#58]
Dear MadAnalysis team,

I'm a beginner with MA5 and I apology if my question is trivial.

I have some troubles to execute the example that you shared in MA5 for expert manual when i try declare my histogram in user.h, here is the trouble that i receive  

said@said-MacBookPro:~/Desktop/MG5_aMC_v2_9_2/HEPTools/madanalysis5/madanalysis5/bin/kkkk/Build$ make
-e --------------------------------------------------------
-e                 Building MadAnalysis Job                
-e --------------------------------------------------------
-e --------------------------------------------------------
-e                       Compilation                       
-e --------------------------------------------------------
g++ -Wall -O3 -fPIC -I/home/said/Desktop/MG5_aMC_v2_9_2/HEPTools/madanalysis5/madanalysis5/tools/ -I./ -pthread -m64 -I/usr/include/root -o Main/main.o -c Main/main.cpp
In file included from ./SampleAnalyzer/User/Analyzer/analysisList.h:1:0,
                 from Main/main.cpp:12:
./SampleAnalyzer/User/Analyzer/kkk.h:18:3: error: ‘TH1F’ does not name a type
   TH1F* Histo_cos;
   ^

**Comment by jackaraz** [comment]
Hi @GHOUAID, you are trying to use ROOT framework to prepare plots. This is a third party software attachment and not Ma5's native plotting tool. Thus for details on how to use ROOT please refer to ROOT's manual.

**Comment by GHOUAID** [comment]
Thank you Jack,
i have one more question, is there  a MA5(expert mode ) way to save  histograms,  instead using functionalities included in the Root library that we code in Finalize method?

**Comment by jackaraz** [comment]
Hi @GHOUAID, of course, please see [this tutorial](https://indico.cern.ch/event/955391/contributions/4087998/). Its slightly
outdated but should help you with the main idea. You can also run normal mode analyses and read how the code is written to learn more about how to deal with expert mode. Normal mode uses expert mode in the background its basically wrapped with a user interface to make it simpler. Additionally we have tons of examples in [PAD](http://madanalysis.irmp.ucl.ac.be/wiki/PublicAnalysisDatabase) which includes analyses both for Delphes and SFS based recasts that you can read and learn how to write an expert mode analysis.

**Comment by GHOUAID** [comment]
the process of using MA5 normal mode analyses and read the code C++ written, but when i start use same code turned, when i use command make in the terminal the code execute without erreur,  but the problem i don't receive any histogram.
one thing that i want to know is the C++ code that i receive using normal mode i should modified it to get save Histogram of my analysis(also i have added my sample event in input.txt)?

**Comment by jackaraz** [comment]
Hi @GHOUAID, please follow the tutorial that I sent the expert mode codes are already provided with the tutorial and it shows how to produce exact plots that I presented there. Expert mode outputs the histograms in SAF format which is a raw histogram output includes all the binning information that you need to plot your results by reading it. It does not make pretty plots thats why its called expert mode, you need to do the work.In normal mode all this is done in the background the analysis structure is exactly the same.

**Comment by GHOUAID** [comment]
thank you Jack

**Comment by GHOUAID** [comment]
Dear Jack,
i am trying to plot my SAF format (histos.saf ) using script that montion in GitHub for plotting specifically jupyter/Using Matplotlib with SafReader.ipynb. during this process i receive some issue  when i import src.SafRreader as shown below, 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_7958/890170756.py in <module>
----> 1 import src.SafReader as sr

ModuleNotFoundError: No module named 'src'

also the jupyter script that i use here


import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import os
import sys
module_path = os.path.abspath(os.path.join('/home/said/Desktop/HISTOS/src'))
if module_path not in sys.path:
    sys.path.append(module_path)

import src.SafReader as sr

**Comment by GHOUAID** [comment]
please, is there a script that your team implement to read this extension .saf
