### ISSUE TITLE
How to extract reconstructed (through Delephs) 4-vectors of final state particles? 

### ISSUE THREAD

**Issue by simonp33** [MadAnalysis/madanalysis5#73]
### Question

Hello,

In my analysis, there are 4 muons as final state particles.
I have performed reconstruction based on MadAnalysis5 through Delphes in reconstruction mode.

What i want to do is to extract 4-vectors (px, py, pz, E) of each final state muons.
To be more specfic, i want to extract 4-vector or muon as below (example, 10000 events generated): 

No.         px       py     pz     E
1          12       43    12     122
2          21       32      58    101
3          12       55      28     109
...
10000   20      48       55      112

For this purpose, how can i get this 4-vectors of muons.
Is there any command in MadAnalysis5 for this? 
Location of file which includes 4-vectors information?
Other methods?..

Thank you in advance.

Sincerely,
Kihong Park

**Comment by jackaraz** [comment]
Hi @simonp33, you can either use the `plot` command or you will need to use the expert mode to extract all the information you need. There is no specific command to extract raw four-momentum data.

**Comment by simonp33** [comment]
Thank you very much for your answer!
