### ISSUE TITLE
fails to complie on ubuntu emulator

### ISSUE THREAD

**Issue by Efffrit** [MadAnalysis/madanalysis5#79]
### System Settings

On windows 10 using Python 3.8.10, g++ and gcc 9.3.0, MA5 release : 1.9.60. Using ubuntu on windows emulator.

### Describe the bug

launched ma5.py in bin, fails at stage 6. 

Is cygpath a command I should have? It doesn't recognise it when I type it in the command line, and when I google it it comes up with a cygwin program for windows.

### To Reproduce

launch madanalysis.

### Log files

/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config: line 60: cygpath: command not found
/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config: line 337: test: command: integer expression expected
/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config: line 428: cygpath: command not found
/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config: line 567: cygpath: command not found
g++ -Wall -O3 -fPIC -I/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/ -MD -GR -GX -G5 -I'' -o root/TreeReaderBase.o -c root/TreeReaderBase.cpp
g++: error: root/TreeReaderBase.o: No such file or directory
g++: error: unrecognized command line option ‘-GR’; did you mean ‘-R’?
g++: error: unrecognized command line option ‘-GX’; did you mean ‘-X’?
g++: error: unrecognized command line option ‘-G5’
/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config: line 60: cygpath: command not found
/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config: line 337: test: command: integer expression expected
/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config: line 428: cygpath: command not found
/mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/ExternalSymLink/Bin/root-config: line 567: cygpath: command not found
make: *** [Makefile_root:90: root/TreeReaderBase.o] Error 1

### Additional information

with -d active, gets this far into component 6:

MA5:    Component 6/9 - library: interface to Root
MA5:      - Cleaning the project before building the library ...
MA5-DEBUG: LogFile: /mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/Interfaces/mrproper_root.log
MA5-DEBUG: Makefile: Makefile_root
MA5-DEBUG: Command: make mrproper --file=Makefile_root
MA5:      - Compiling the source files ...
MA5-ERROR: impossible to compile the project. For more details, see the log file:
MA5-ERROR: /mnt/c/Users/Jack/OneDrive/Documents/MG5_aMC_v3_3_1/MadAnalysis5_v1.9.60/madanalysis5/tools/SampleAnalyzer/Interfaces/compilation_root.log
MA5-ERROR: The library building aborted.

**Comment by jackaraz** [comment]
Hi @Efffrit, this seems to be a ROOT related issue, please check if you satisfy all the requirements that ROOT has from their website and/or manual. Alternatively, if you do not need ROOT, you can disable it from here:
https://github.com/MadAnalysis/madanalysis5/blob/8fd06645e329ad18d46d46e290bcae54039696c9/madanalysis/input/installation_options.dat#L10-L12

Note that MadAnalysis only uses ROOT within Delphes interface so you will need ROOT version 6 which is required by Delphes.

**Comment by Efffrit** [comment]
Thanks, that's super helpful, I updated ROOT to the most recent version and now it's working
