### ISSUE TITLE
How do I make my histograms with outlines overlayed? 

### ISSUE THREAD

**Issue by rohanshenoy** [MadAnalysis/madanalysis5#81]
### Question

Hello, when I plot with root ,and matplotlib, my histograms are filled in histograms stacked on top of each other, but this is very difficult to understand on a log scale. How do I make the plots overlayed on top with only the histogram outlines being showed.

Here is what I would like my plots to look like. Slide 16 here: https://indico.in2p3.fr/event/5905/contributions/35909/attachments/28776/35453/Introduction2MadAnalysi5.pdf

Thank you

**Comment by BFuks** [comment]
Hi,

You can type the following in the CLI:
  ```ma5> set main.stacking_method = superimpose```
Those options are well documented in the manual, which you could check for more information.

Regards,

Benjamin

**Comment by rohanshenoy** [comment]
Thank you!
