### ISSUE TITLE
Custom histo normalization

### ISSUE THREAD

**Issue by dionysisskouras** [MadAnalysis/madanalysis5#82]
### Question

Hello 
I have generated some histos in Normal Mode after importing files , not writing code in ma5. 
I want to normalize my histos to xsection*integrated luminosity. Is there any way to do that?
Thank you 
Dionyisis

**Comment by BFuks** [comment]
Hi Dionysis,

This should be accounted for at the post-processing of the MA5 output. There is no need to worry about this at the level of the analysis code.

Cheers,

Benjamin

**Comment by BFuks** [comment]
Hi,

From the output file, you know the content of every bin of a histogram in terms of the weights provided in the input event file. A normalisation to the right luminosity is then just a matter of a simple multiplication.

Cheers,

Benjamin

**Comment by dionysisskouras** [comment]
Yes
I have two datasets which I plot with madanalysis in Hadron Mode. I plot standard kinematics such as Met, Tht, pT etc. Now, I want to normalize all my plots to (cross section * integrated luminosity)  / number of events. Is there a way to do that without going into Expert mode?

**Comment by jackaraz** [comment]
Hi @dionysisskouras, of course as I said this is the most basic thing that you can do in MadAnalysis. First, you need to set the cross-section value [pb] of each sample (if not MadAnalysis extracts the info from your sample file if exists). Then you need to tell the luminosity value that you want, by default MadAnalysis uses 10 fb$^{-1}$. Then you need to tell how you like it to be normalised, i.e. `lumi_weight`. That's it. These are all documented in the manual, tutorials and the cheatsheet in `doc` folder.

**Comment by dionysisskouras** [comment]
Thanks a lot and sorry for the confusion, I am very new to this

**Comment by jackaraz** [comment]
no worries, please let us know if you have any other questions. Closing this issue.
