### ISSUE TITLE
Missing new particle in MET histogram'.

### ISSUE THREAD

**Issue by manisharma123456** [MadAnalysis/madanalysis5#9]
**Before posting a question**
Search existing [GitHub issues](https://github.com/MadAnalysis/madanalysis5/issues) or [Launchpad](https://answers.launchpad.net/madanalysis5) to make sure the issue does not already exist.

For general technical details check out our [documentation](http://arxiv.org/abs/1206.1599), [tutorials](https://madanalysis.irmp.ucl.ac.be/wiki/tutorials), [FAQs about Normal Mode](http://madanalysis.irmp.ucl.ac.be/wiki/FAQNormalMode) and reference cards provided under `doc` folder.

**System Settings:**
 - OS: [e.g. macOS v12.1]
 - Python version
 - gcc/c++ version
 - MadAnalysis 5 version
 - If applicable, versions for other third party software i.e. Fastjet, Delphes, pyhf etc.

**Comment by manisharma123456** [comment]
Hi,
I have recently started using MA5..
I tried to produce a histogram of missing energy, but it is not considering my new particle in it as signal. However, chi is not defined as a particle in hadron mode, but still it is not shown in missing energy histogram....I tried with both LHE and HEPMC files...

please let me know how to solve it to include new particle in the missing energy histogram..

Thankyou.

**Comment by jackaraz** [comment]
Hi @manisharma123456 you can add a new invisible particle by typing
```
ma5> define invisible = invisible <particle PDGID>
```
this will include the current invisible particle list and add your particle to the list as well. Please check our [documentation](http://arxiv.org/abs/1206.1599) and [tutorials](https://madanalysis.irmp.ucl.ac.be/wiki/tutorials) these are all written there.

Cheers

**Comment by manisharma123456** [comment]
Thanks, this helped.
