### ISSUE TITLE
RegionSelectionManager does not free memory in regions_ vector.

### ISSUE THREAD

**Issue by kfan326** [MadAnalysis/madanalysis5#98]
### System Settings

macOS

### Describe the bug

destructor should include:

for(auto &region_pointer : regions_){
    delete region_pointer;
}

### To Reproduce

destructor should include:

for(auto &region_pointer : regions_){
    delete region_pointer;
}

**Comment by jackaraz** [comment]
Hi @kfan326, could you please include more details about the bug? It is important to keep a detailed record of the issues with the code.

**Comment by kfan326** [comment]
> Hi @kfan326, could you please include more details about the bug? It is important to keep a detailed record of the issues with the code.

Of course.

in RegionSelectionManager.h : line 133, 134

```
    RegionSelection* myregion = new RegionSelection(name);
    regions_.push_back(myregion);
```

pointer to RegionSelection objects are pushed into the regions_ vector on line 54. Destructor only capable of handling stack allocated objects. Currently, once RegionSelectionManager object is out of scope, references to RegionSelection objects will be lost, resulting in memory leak. Destructor will be able to handle deletion of RegionSelection objects once code is added.
